/**
 * The backlog, as data. `tools/build-backlog.mjs` renders it to NOTES/backlog.html, which is
 * the page Mariia actually reads.
 *
 * Editing rules, so this stays cheap to keep current:
 *  - status: 'next' | 'wait' | 'later' | 'done'. Finishing something is a one-word change.
 *  - A done item stays where it is written and the renderer moves it into Done, permanently.
 *    Nothing is deleted, and nothing has to be re-typed to record that it landed.
 *  - 'wait' means somebody outside this repo owes a reply. Those are gathered into Waiting on
 *    somebody as well as shown in place, because that list is the one to chase.
 *  - `why` is the one line that explains why the item exists. Write it for a reader who was
 *    not in the meeting.
 */

export const updated = '2026-09-01';

export const quick = {
  title: 'Quick actions',
  hint: 'No discussion needed.',
  items: [
    { t: 'What each assessor sees of the pool', status: 'wait', owes: 'Dan or Chris',
      why: 'Everything, for now. Chris says departments know who their assessor is, so they could pick one at submission, and an assessor could share a file or hand it on. Until that is decided, every assessor sees the whole pool, and a My assessments tab is the filter to add when the rule exists.' },
    { t: 'Stand up the store', status: 'next',
      why: 'The Worker is written and waiting in deploy/worker.js, and the page takes its address as a build input. What is left is a Cloudflare account, which only you can create: sign in, paste the file, bind a KV namespace, then build with EARB_ENDPOINT set.' },
    { t: 'Decide where the tool is published', status: 'next',
      why: 'canada-ca/TBS-OCIO-ESP already publishes a tool as one index.html in a folder, and you already have push access. One commit puts this at canada-ca.github.io/TBS-OCIO-ESP/earb-self-assessment/, with no new repo and no transfer. The repo is public, so Dan has to clear the 176 draft questions being visible first.' },
    { t: 'The marking question is about the evidence', status: 'done',
      why: 'The assessment is always unclassified, so asking how the assessment is marked was the wrong question. It asks for the highest marking of the artefacts the answers point at, which is what an assessor needs access to.' },
    { t: 'The banner stops printing the wrong marking', status: 'done',
      why: 'Choosing Protected A stamped PROTECTED A across an unclassified document, top, bottom and every printout. It reads UNCLASSIFIED with "evidence up to Protected A" beside it.' },
    { t: 'The email subject line is readable', status: 'done',
      why: 'It said "EARB evidence - m - [question]", with a placeholder nobody filled in. It now names what it is, the initiative and the question number, and the evidence box offers a Copy button.' },
    { t: 'The save badge says there is no online copy', status: 'done',
      why: 'She asked where to save online. There is nowhere, and the badge now says so on hover instead of leaving "draft saved" to be read as the whole story.' },
    { t: 'A library of question sets', status: 'done',
      why: 'Sets accumulate. Settings lists every one this browser holds and marks the one in use. Adding one changes nothing on its own, and each row has a menu: preview the questions, make it active, delete it, and who added it. Deleting is two steps and refused only on the set in use and on the last remaining set.' },
    { t: 'Each submission is scored against its own question set', status: 'done',
      why: 'Twenty submissions answered against set 1 are untouched when set 2 becomes active, but the assessor page used to recompute them with whichever set was active and print a one-line notice. It now uses the set they were answered against when this browser holds it, names that set on every row, and says what it did. CSV export writes one file per set, because the columns are question ids.' },
    { t: 'An assessor screen with nothing in it says why', status: 'done',
      why: 'Three different situations, and an assessor can tell them apart: no shared store exists yet, this machine cannot reach it, or it is reachable and empty. With a cat.' },
    { t: 'Sign in is one screen, and short screens keep their footer', status: 'done',
      why: 'The footer floated in the middle of any short page, the sign-in scrolled like a document, and the load-submissions card hung off the top edge.' },
    { t: 'Email subjects use a code, not the initiative name', status: 'done',
      why: 'A sent email cannot be un-sent, so a subject line that carries the initiative name breaks the moment somebody renames the initiative. Every assessment gets a four-character reference when it is created, the subject reads "EARB evidence 7QF3, question B-Q1", and renaming costs nothing. It shows on the overview beside the name and on the assessor row.' },
    { t: 'Not applicable folds the work away and keeps it', status: 'done',
      why: 'A question with evidence on it turned into a grey slab when it was marked not applicable: the disclosure opened itself because there was something inside, and the whole apparatus dimmed. It folds, the summary says the work is kept and not counted, and unticking puts it back. Deleting somebody evidence because they ticked a box is not the tool decision to make.' },
    { t: 'The revert goes to the highest marking allowed', status: 'done',
      why: 'Saying no to a Protected C piece put the row back to unmarked instead of the marking chosen on the overview.' },
    { t: 'The backlog opens from Settings', status: 'done',
      why: 'A This build pane, with the tool version, the question set version, whether there is a store, and the link.' },
    { t: 'The assessor side keeps its work in the browser', status: 'done',
      why: 'Every audited score, verdict, note and history entry used to live in memory until the file was saved, so a reload took the afternoon. It autosaves the way the submitter side always has, Clear asks first, and the session comes back after a reload.' },
    { t: 'The store is one build input away', status: 'done',
      why: 'EARB_ENDPOINT sets both the address the page writes to and the one origin its security policy allows, so a build with no endpoint still cannot make a request. deploy/worker.js is the store: forty lines, free tier, browser-only setup.' },
    { t: 'A prompt when the evidence outranks the overview answer', status: 'done',
      why: 'Marking a piece of evidence higher than the answer given on the overview used to sit there blocking the save. It asks which of the two is wrong, and raising the overview answer does not re-open the pledge.' },
    { t: 'Every dialog closes on a click outside it', status: 'done',
      why: 'Menus stayed open until something else was clicked, and the discard window had no way out but its own buttons. Cancelling is the outcome, so a stray click can never delete. The classified pledge is the exception, because a tick is the point of it.' },
    { t: 'One dialog everywhere, and no silent yes', status: 'done',
      why: 'A browser without dialog support fell back to window.confirm, which named neither the count nor the stake and treated OK as yes. The same dialog renders in place instead, so the tests press the real buttons too.' },
    { t: 'A filled section stops looking empty', status: 'done',
      why: 'The disclosure said "Add reasoning or evidence" whether or not anything was inside. The heading is stable now and a status follows it, the way a government task list marks a section as started.' },
    { t: 'Done asks the reader to finish, and says what is missing', status: 'done',
      why: 'Pressing Done on the overview with something empty repainted the same card and explained nothing. It goes to the gap and names it, and what is left is listed under the step at all times.' },
    { t: 'The cat had horns, and then its mouth crossed its body', status: 'done',
      why: 'First the head outline peaked at both sides, which were the ears, and two more thin triangles were drawn floating above them. Then the mouth arc sat on the body top edge and the two curves read as one line. Ears joined to a round head, face eight units clear of the body.' },
    { t: 'A classified file cannot be left attached', status: 'done',
      why: 'Hiding the attach control was not enough: attach while the row is unclassified, raise the marking afterwards, and the file stayed, saved, and passed every check. The save is blocked now and the row says why, which is the one promise the pledge window makes.' },
    { t: 'The email note is a field, and keeps the line that was sent', status: 'done',
      why: 'It was a prefix on the location text, so editing that text by hand changed the state, and renaming the initiative made the recorded subject and the shown subject disagree. There is also a way to take the note back.' },
    { t: 'The empty evidence row stops blocking the save', status: 'done',
      why: 'Add evidence created a row with no marking, and the save gate demanded one immediately. An empty row is nothing to mark. A classified row no longer offers attaching at all, and a row already recorded as emailed does not offer it either.' },
    { t: 'Question ids lose a letter', status: 'done',
      why: 'BU-Q1 is now B-Q1. The four domain initials are distinct, so the second letter carried nothing. Cheap today because no real submission exists; expensive once ids are column names in somebody exported spreadsheet.' },
    { t: 'Nothing is destroyed in one step', status: 'done',
      why: 'An audit found twenty destructive actions and eleven of them destroyed something with no prompt at all. Every one now asks, keeps a copy where it can, or leaves the work alone.' },
    { t: 'Not applicable hides the scale and keeps the score', status: 'done',
      why: 'The eleven descriptions explain a score, and a question that does not apply has none. Ticking the box also used to erase the score, and unticking did not give it back.' },
    { t: 'The frame stops reading as part of the page', status: 'done',
      why: 'Measured: the header separated from the page by 1.13 to 1 in light and 1.08 to 1 in dark, and the page footer was exactly the page colour. The frame has its own edge token, the dark frame is now lighter than the page instead of darker, the footer has a ground, and a shadow appears only once content scrolls under it.' },
    { t: 'The rail stops repeating the domain tabs on a narrow screen', status: 'done',
      why: 'Below 860px the rail lies down into a strip under the tabs. On the overview it had no section rows to show, so the same five items appeared twice. Found while checking the marking banner on the live page.' },
    { t: 'The prose linter takes any file', status: 'done',
      why: 'The writing rules were being applied from memory for chat replies, and em dashes went out. Replies go through the same linter as the app copy now.' },
    { t: 'Backlog gets jump links and a Done section that stays', status: 'done',
      why: 'Done was at the bottom of eight layers with no way to reach it. Every section now has a link at the top, and Done is split into what came after Dan’s review and what he had already seen.' },
    { t: 'Every backlog item carries its reason', status: 'done',
      why: 'Five items had a title and nothing else, so they read as jargon. All of them now say why they exist.' },
    { t: 'Rail’s Overview row shows a count and a bar', status: 'done',
      why: 'Every other rail row had both; Overview had neither, which reads as a row stuck at zero.' },
    { t: 'Overview bar moves on the first keystroke', status: 'done',
      why: 'It counted the three groups, and group one needs four fields. It now measures the six fields while the count still reads in groups.' },
    { t: 'README and Settings stop describing a local-only tool', status: 'done',
      why: 'Both said the tool cannot transmit and that the repo is private. Neither was true.' },
    { t: 'Settings marks the unbuilt parts as unbuilt', status: 'done',
      why: 'It promised a submit act and a withdrawal path as though both existed. Neither is written, and copy that describes a feature has to say whether the feature is there.' },
  ],
};

export const layers = [
  {
    title: 'Question set', owner: 'Dan',
    groups: [
      { t: 'Answer types and criticality', status: 'wait',
        why: 'The shape of the questions, which Dan called the biggest remaining piece. Our reading is in the tool and labelled provisional.',
        subs: [
          { t: 'Confirm the answer type for every question', status: 'wait',
            why: 'Ten are yes/no on our reading of the wording. The other 166 are scored 0 to 10.' },
          { t: 'Confirm which no answers matter most', status: 'wait',
            why: 'Every no colours its section red today. If some should not, that is his call.' },
          { t: 'Set per-question criticality', status: 'wait',
            why: 'Separate from section weight, and nothing in his workbook carries it.' },
        ] },
      { t: 'Content still owed', status: 'wait',
        why: 'None of this is ours to write.',
        subs: [
          { t: 'Fix the section weights that total 80', status: 'wait',
            why: 'His error, confirmed in his own words. The tool shares the missing 20 proportionally and shows the normalised share.' },
          { t: 'Add security and privacy questions', status: 'later',
            why: 'Neither is represented. A security review is already asking. The topic view makes the gap visible in the meantime.' },
          { t: 'Bring in the dropdown answers', status: 'wait',
            why: 'No picklists exist. Needs the 700 or more past assessments, which only he can hand over.' },
        ] },
    ],
  },
  {
    title: 'Engine', owner: 'us',
    groups: [
      { t: 'Question mechanics', status: 'done',
        why: 'What the instrument can carry.',
        subs: [
          { t: 'Multiple answer types', status: 'done',
            why: 'A type field with scale as the default, so nothing existing breaks.' },
          { t: 'A no answer colours its section', status: 'done',
            why: 'The question, its section, its rail row and its domain tab. It stops nothing.' },
          { t: 'Topic metadata and per-topic roll-up', status: 'done',
            why: 'Security, privacy, cost, data, business and technology, visible without inventing a fifth domain.' },
          { t: 'Two-topic scoring', status: 'done',
            why: 'Once in the overall, at full weight inside each topic, because the weight genuinely differs by topic.' },
        ] },
      { t: 'Storage and concurrency', status: 'next',
        why: 'Everything is unclassified, so it can all live online. The seam is written; the store is not.',
        subs: [
          { t: 'The store seam', status: 'done',
            why: 'src/store.ts. One constant from live, and the dashboard already reads through it.' },
          { t: 'The three calls a real write needs', status: 'done',
            why: 'Saving, saved, failed with a reason. Nothing drives them yet, so the wording is settled before the write exists.' },
          { t: 'One deliberate first submit', status: 'next',
            why: 'You should know the moment your work becomes visible to TBS.' },
          { t: 'Autosave online after that', status: 'next',
            why: 'Like a document. Every later change writes through.' },
          { t: 'Field-level last write wins, with a marker', status: 'next',
            why: 'Not locking. Two people in different questions never collide.' },
          { t: 'Tell the other person it changed under them', status: 'next',
            why: 'The audit trail already keeps both accounts. What is missing is the live signal while somebody is looking at the line.' },
          { t: 'Submitter answers and assessor scores are separate fields', status: 'done', seen: true,
            why: 'Which is why a submitter and an assessor cannot collide at all.' },
        ] },
    ],
  },
  {
    title: 'Interface: the submitter', owner: 'us',
    groups: [
      { t: 'Evidence', status: 'done',
        why: 'The change that follows from unclassified-only.',
        subs: [
          { t: 'Ask for a link', status: 'done',
            why: 'Point at where it lives, and make sure your assessor can open it.' },
          { t: 'Email fallback, with a pattern', status: 'done',
            why: 'Marking, sent by email, subject line written for you, so an assessor can find it.' },
        ] },
      { t: 'The classified pledge, as a modal', status: 'done',
        why: 'She chose Protected A on the strip that says "mark this file to save it" and nothing happened. The advice panel was on a different screen, so it could be scrolled past and was.',
        subs: [
          { t: 'Any marking above unclassified takes over the screen', status: 'done',
            why: 'Whichever control set it. The strip, the picker, and anything added later go through one function, so they cannot drift apart again.' },
          { t: 'The close control is dead until the box is ticked', status: 'done',
            why: 'Grey and unclickable, and it says "tick the box first". Escape does not dismiss it and clicking outside does nothing.' },
          { t: 'The way out changes the answer', status: 'done',
            why: 'An accidental click needs an exit that is not a dismissal: "this is unclassified after all" sets the marking back rather than waving the warning away.' },
          { t: 'It asks once, not every time', status: 'done',
            why: 'After the pledge, switching between classified markings does not ask again. The panel on the overview stays as the reference.' },
          { t: 'The unmarked banner lands on the marking question', status: 'done',
            why: 'It scrolled to an element that only exists on the overview, so from any of the twenty question pages it did nothing at all.' },
        ] },
      { t: 'Marking', status: 'next',
        why: 'Somebody still has to state the marking of what they point at.',
        subs: [
          { t: 'One big unclassified tile, the six grouped behind it', status: 'done',
            why: 'The default must not be taxed by the rare path.' },
          { t: 'Classified panel with an acknowledgement toggle', status: 'done',
            why: 'What to do instead, at the moment it is relevant.' },
          { t: 'Collapse three pickers into one', status: 'next',
            why: 'The footer’s seven pills bypass the whole design.' },
        ] },
      { t: 'Submitting', status: 'next',
        why: 'The moment work stops being private. Everything here is about the person knowing that.',
        subs: [
          { t: 'First-submit confirmation', status: 'next',
            why: 'Names what is about to go online and asks them to confirm it is unclassified.' },
          { t: 'Save status indicator', status: 'done',
            why: 'Draft in browser, saving, saved, or not saved with a reason. It sits in the header now, so it is on every screen and on a phone; it was on the 21 question pages only, and CSS hid it below 720px.' },
          { t: 'Silent until something is actually written', status: 'done',
            why: 'It opened at "draft saved in browser" on an empty page, which is a claim ahead of the fact.' },
          { t: 'One live indicator, not one per repaint', status: 'done',
            why: 'Each repaint added another listener holding a dead node. Harmless while the state never changed, and a leak the moment writes start.' },
        ] },
    ],
  },
  {
    title: 'Interface: the assessor', owner: 'us',
    groups: [
      { t: 'Identity', status: 'wait',
        why: 'Their name goes against a number somebody may dispute.',
        subs: [
          { t: 'Mockup verification screen', status: 'done',
            why: 'Labelled a mockup, the departmental-account button visibly disabled, everything unverified.' },
          { t: 'Real sign-in', status: 'wait', owes: 'Dan',
            why: 'Blocked on how identity gets checked at all, which is his answer to give.' },
        ] },
      { t: 'Nothing an assessor typed is overwritten silently', status: 'done',
        why: 'Four places did it. Agree-with-all replaced a verdict somebody had already given, the note field rewrote the reason on whatever change was last in the trail, reloading a file of the same name discarded the audit attached to it without a word, and the email button wrote over a link somebody had typed.' },
      { t: 'Auditing rules Dan gave as rules', status: 'done',
        why: 'He stated these as requirements in the review, not as ideas. All five are built.',
        subs: [
          { t: 'Justification required on a changed score', status: 'done',
            why: 'His rule. The file cannot be saved while one is missing, and the button says how many are outstanding.' },
          { t: 'Accept-all per section', status: 'done',
            why: 'He asked for it by name. It touches no score, and skips any changed score that still needs a reason.' },
          { t: 'Assessor recorded per question', status: 'done',
            why: 'Two assessors on one high-profile file. Each change carries a name, a time and a reason.' },
          { t: 'The edit exchange, visible', status: 'done',
            why: 'The line says it was edited and by whom. The full back and forth opens on request, and nothing is overwritten.' },
          { t: 'Evidence read-only', status: 'done',
            why: 'Already true, and now held true by a test.' },
        ] },
      { t: 'Load a question set moves here', status: 'done',
        why: 'It belongs to whoever maintains the instrument. A submitter is told where it lives and not handed the control.' },
    ],
  },
  {
    title: 'Interface: admin', owner: 'us',
    groups: [
      { t: 'Reachable without going through the assessor view', status: 'done',
        why: 'It sat behind two clicks on the assessor side with nothing on the start page pointing at it. There is a line under the assessor link now, and it asks who you are the same way.' },
      { t: 'The portfolio dashboard', status: 'done',
        why: 'Dan’s self-updating dashboard. It recalculates every record from the answers as the page draws, so there is no stored number to go stale.',
        subs: [
          { t: 'Averages by domain and by topic', status: 'done',
            why: 'The topic cut is the one a single assessment cannot show: security spread thin over four domains looks fine in each of them.' },
          { t: 'Every record, weakest first', status: 'done',
            why: 'The list is a worklist. Red rows are the ones with a no answer.' },
          { t: 'Portfolio CSV', status: 'done',
            why: 'One row per record, topic columns included.' },
          { t: 'It says what it can currently see', status: 'done',
            why: 'With no store, that is this browser and the files opened this session. The page says so rather than looking live.' },
        ] },
      { t: 'Admin-only actions', status: 'wait', owes: 'Dan',
        why: 'Nobody has decided whether admin is a role. Listed so the roles matrix is complete.',
        subs: [
          { t: 'Withdraw a record', status: 'later',
            why: 'Out of every statistic, still in the list. Nothing is deleted.' },
          { t: 'Re-assign an assessor', status: 'later',
            why: 'Somebody leaves, or a file needs a second pair of eyes.' },
          { t: 'Clear out test submissions', status: 'later',
            why: 'Dan raised it and parked it.' },
        ] },
    ],
  },
  {
    title: 'Interface: the executive view', owner: 'us',
    groups: [
      { t: 'Dan’s twelve-month questions', status: 'later',
        why: 'The reason the data is worth capturing at all. All of it needs more than one record to mean anything.',
        subs: [
          { t: 'Per-question averages and histograms', status: 'later',
            why: 'Which questions the whole GC is weak on, which is the argument for changing a question rather than a department.' },
          { t: 'Average by department', status: 'later',
            why: 'Needs enough records that a department average is not one initiative.' },
          { t: 'Best and worst evidence per question', status: 'later',
            why: 'Gives a submitter an example of what good looks like, which is the thing people ask for first.' },
        ] },
    ],
  },
  {
    title: 'Data and hosting', owner: 'us and TBS',
    groups: [
      { t: 'Get into canada-ca', status: 'next',
        why: 'Access is done. Publishing is a commit away in a repo you can already push to. A repo of our own is a separate, slower question.',
        subs: [
          { t: 'Publish into canada-ca/TBS-OCIO-ESP', status: 'next',
            why: 'One folder holding one index.html, the same shape as earb-forward-agenda, which that repo already serves. Needs Dan to clear the questions being public.' },
          { t: 'GitHub Pages cannot serve a private repo on a free account', status: 'done',
            why: 'Checked: all 35 Pages sites in canada-ca come from public repos, and no private repo there serves one. This is why a separate public preview repo exists.' },
          { t: 'Reply to Nick: transfer the existing repo', status: 'done',
            why: 'Sent. 28 commits of history, all yours.' },
          { t: 'Nick’s answer on who performs the transfer', status: 'wait', owes: 'Nick',
            why: 'Open an issue on canada-ca/welcome is the route he named. Whether he moves it or you do is the part still unanswered.' },
          { t: 'Retire the separate preview repo', status: 'next',
            why: 'Pages can come from the canada-ca repo once it exists.' },
        ] },
      { t: 'Where submissions land', status: 'next',
        why: 'Dan asked us to figure it out. GitHub Pages serves static files and cannot accept a write, so something has to receive one.',
        subs: [
          { t: 'A write endpoint', status: 'next',
            why: 'An Azure Function is the cheapest route: canada-ca/TBS-OCIO-ESP already builds through Azure Pipelines, so the account and the approval path exist.' },
          { t: 'Open the CSP to exactly that origin', status: 'next',
            why: 'One line in build.mjs. The page blocks every outbound request until then.' },
          { t: 'Per-user auth', status: 'later',
            why: 'The known limit. Microsoft Entra is the obvious route, since departments already sign in with it.' },
        ] },
      { t: 'Notifications', status: 'wait',
        why: 'GC Notify is the sanctioned service and is already in Dan’s own rubric at application question Q33. What triggers one is his decision and he has not made it.',
        subs: [
          { t: 'Draft the email', status: 'done', seen: true,
            why: 'Opens the person’s own mail client with the message written. All a static page can do.' },
          { t: 'Decide the triggers', status: 'wait', owes: 'Dan',
            why: 'Submission, assignment, a changed score and a reminder are four different decisions.' },
        ] },
    ],
  },
  {
    title: 'Process, for people', owner: 'Dan and John',
    groups: [
      { t: 'How John’s team validates evidence', status: 'later',
        why: 'Their job changes completely and Dan expects resistance.' },
      { t: 'What the intake accepts, and from whom', status: 'later',
        why: 'Dan called it a protocol for the humans.' },
      { t: 'Which initiatives must submit', status: 'later',
        why: 'His call. Blocks nothing we build.' },
    ],
  },
];

export const resolved = [
  { q: 'Should the tool hold classified information?',
    a: 'No. Nothing protected or classified goes in at all, settled with Dan on 1 September. That removed the second deployment, the local-only engine, the theme switch, and the whole recall problem.' },
  { q: 'What happens to online data when a marking rises?',
    a: 'Dropped. The tool never stores classified evidence, so the question cannot arise.' },
  { q: 'Does a two-topic question count twice overall?',
    a: 'No. Once in the overall score, and at full weight inside each topic, which is where the weights genuinely differ.' },
  { q: 'File sharing for a team filling one in together?',
    a: 'No files. Everything is online, so version control stops being a problem the tool has to solve.' },
  { q: 'Deletion rights',
    a: 'Nothing is ever hard-deleted. A record is withdrawn and left out of the statistics.' },
  { q: 'One build or two?',
    a: 'One. Submission is a capability the hosting turns on.' },
  { q: 'Where the plan lives',
    a: 'This page. The Markdown version is deleted.' },
  { q: 'Org access to canada-ca',
    a: 'Done. Nick invited you, and the TBS-OCIO-ESP team gives push access to canada-ca/TBS-OCIO-ESP.' },
  { q: 'Who may replace the question set?',
    a: 'The assessor and admin side only. Loading one clears every answer, so a submitter is told where it lives and not handed the control.' },
  { q: 'How does the dashboard stay current?',
    a: 'By storing nothing. It recalculates each record from its answers as the page draws, so there is no roll-up that can go stale.' },
];

export const questions = [
  { q: 'What an assessor sees of the pool', who: 'Dan or Chris',
    blocks: 'Filtering, and any My assessments view', meanwhile: 'Every assessor sees everything' },
  { q: 'Who may write to the prototype store', who: 'us, then Dan',
    blocks: 'Nothing yet', meanwhile: 'Anybody who reads the page source. Fine for unclassified drafts, and the reason the real one needs the departmental sign-in' },
  { q: 'Can the 176 draft questions be public', who: 'Dan',
    blocks: 'Publishing inside canada-ca', meanwhile: 'The preview sits on a personal public repo, which is the same exposure with less visibility' },
  { q: 'Who may edit a stored assessment, and how it is checked', who: 'Dan',
    blocks: 'Real authentication', meanwhile: 'Mockup screen, everything labelled unverified' },
  { q: 'Verifying an assessor’s identity', who: 'Dan',
    blocks: 'Real sign-in', meanwhile: 'Typed name, labelled unverified on every change it records' },
  { q: 'Is admin a role, or an assessor with more buttons?', who: 'Dan',
    blocks: 'The admin-only actions', meanwhile: 'The dashboard is built; the actions are listed and marked unbuilt' },
  { q: 'Notification triggers and recipients', who: 'Dan',
    blocks: 'Notifications', meanwhile: 'Draft the email. GC Notify is the sanctioned route' },
  { q: 'Which questions are yes/no, and which no answers matter most', who: 'Dan',
    blocks: 'Nothing', meanwhile: 'Ten on our reading, labelled provisional in the app' },
  { q: 'The routing thresholds', who: 'Dan',
    blocks: 'Nothing', meanwhile: 'Interpolated between two numbers he named, labelled provisional' },
  { q: 'Which initiatives must submit', who: 'Dan',
    blocks: 'Nothing', meanwhile: 'Ignore for now' },
  { q: 'Who performs the canada-ca transfer', who: 'Nick',
    blocks: 'The repo move', meanwhile: 'Asked. An issue on canada-ca/welcome is the route he named' },
  { q: 'What the production intake should be', who: 'TBS',
    blocks: 'Production only', meanwhile: 'The prototype answer is an Azure Function plus one CSP line' },
];
