/**
 * The backlog, as data. `tools/build-backlog.mjs` renders it to NOTES/backlog.html, which is
 * the page Mariia actually reads.
 *
 * Editing rules, so this stays cheap to keep current:
 *  - status: 'next' | 'wait' | 'later' | 'done'. Finishing something is a one-word change.
 *  - A done item stays where it is written and the renderer moves it into Done, permanently.
 *    Nothing is deleted, and nothing has to be re-typed to record that it landed.
 *  - 'wait' means somebody outside this repo owes a reply. Those are gathered into Waiting on
 *    somebody as well as shown in place, because that list is the one to chase.
 *  - `why` is the one line that explains why the item exists. Write it for a reader who was
 *    not in the meeting.
 *  - tier: 'level2' marks something deliberately after the prototype. An item with no tier is
 *    in the prototype, because most of this file is and tagging every one of them is a habit
 *    the next editor drops. Only write 'level2' where somebody decided it, and say in `why`
 *    who decided it and when.
 */

export const updated = '2026-09-21';

export const quick = {
  title: 'Quick actions',
  hint: 'No discussion needed.',
  items: [
    { t: 'The tool is half bilingual, and the assessor side is not bilingual at all', status: 'next', tier: 'mvp',
      why: 'Reported as: in submitter view there is no french text whatsoever, the french toggle is present. The toggle works; the screen it was tried on is 8 per cent chrome. Measured on the built pages, visible characters that change when French is asked for: the start page 84 per cent, the overview 73, a questions page 8, the results page 3, the assessor list 2, an open submission 0.06. Three separate things are inside that. One, our own wording that never went through t(): about 380 strings on the submitter and shared side and 138 on the assessor side, where views-review.ts and views-dashboard.ts make no t() call at all. That is three to four days plus a day of review for the submitter side and a day and a half plus half a day for the assessor side, and it waits on nobody. Two, the question set, which is 3,356 words of Dan\u2019s English with no field anywhere to hold a French version: two days of build work for the format, the validator, the importer and the lock file, and it cannot start until the French text exists. Three, things that stay English on purpose: the access code, the question ids, which are spreadsheet column names, and this page. The part that landed on 21 September was the accessibility half: the set now says it is English inside a page that says it is French, so a screen reader stops reading 23,236 characters of English in a French voice.' },
    { t: 'Ask Dan for the French of the question set', status: 'wait', owes: 'Dan', tier: 'mvp',
      why: '3,356 words, and the Translation Bureau on instrument text of that size is weeks, so it is the long pole and the ask should go now. It breaks down as 2,696 words of the 176 questions, 236 for the eleven rungs of the scale, which is the ladder a submitter reads to pick a score, 113 for the routing and maturity bands, 105 for the twenty section names and four domain names, 91 for the seven lifecycle stages, 89 for the five categories and 26 for the title and the rest. Two decisions in it are his and not ours. Whether the French is a second file or extra fields in the one file, given that the ids are spreadsheet column names and rubric-ids.lock.json has to stay identical either way. And who signs off the wording, because a self-assessment whose questions differ between the two languages is two instruments.' },
    { t: 'Friday: which of three ways Dan sees the assessor side', status: 'wait', owes: 'Dan', tier: 'mvp',
      why: 'He picks, because two of the three cost him something and that is his to weigh. One, he gives a Google address and is added as an assessor: the real store, the real pool, the real screens, one form and under a minute, nothing built and nothing published. It is a personal address holding a grant on a government prototype, he gets the top rung, which includes deleting any record and removing any assessor, and access can be taken away afterwards in the danger zone. Two, the demonstration page, which needs no account at all: the real screens against four invented submissions, no store address compiled into it, nothing kept. Three, he watches while somebody signed in drives. The submitter side needs no decision at all and never has: the access code is the record\u2019s own name in the store, so holding the code is the credential, and he can fill one in today with no account.' },
    { t: 'Check the Google sign-in accepts an address from outside the project', status: 'next', tier: 'mvp',
      why: 'Two minutes in the Firebase console, Authentication, Sign-in method, Google, and it decides whether the first Friday option exists at all. If the Google Cloud consent screen was ever set to Internal, or left in Testing with a named list of test users, an address that is not on that list is refused at the provider before the tool sees it, and what the person gets is a sign-in problem with no explanation.' },
    { t: 'Put something in the real pool before Friday', status: 'next', tier: 'mvp',
      why: 'There is no seeding tool, so test submissions are made through the submitter page, which needs no account, and sent. Half an hour. Without it an assessor signs in to an empty list, and an empty list reads as a broken tool rather than an empty one.' },
    { t: 'What each assessor sees of the pool', status: 'wait', owes: 'Dan or Chris',
      why: 'Everything, for now. Chris says departments know who their assessor is, so they could pick one at submission, and an assessor could share a file or hand it on. Until that is decided, every assessor sees the whole pool, and a My assessments tab is the filter to add when the rule exists.' },
    { t: 'Sign in and see the pool', status: 'next',
      why: 'You did the consent screen and got a blank page, which was our bug and is fixed. The gate that decides whether to show the sign-in read one variable and the Google sign-in wrote another, so the page drew the sign-in, noticed you were already signed in, and redrew itself until the browser gave up. Two more of the same family went with it: the assessor screen never read the store at all, so a submission sitting in it was reported as an empty pool, and nothing read your role, so every account was offered the admin screen. All three are held by a new suite that builds the way the published page is built.' },
    { t: 'Restrict the browser key, then close the GitHub alert', status: 'next',
      why: 'The one thing left on the store that only you can do. Google Cloud console, Credentials, the browser key Firebase made: websites myermcat.github.io and localhost, APIs Identity Toolkit, Token Service and Cloud Firestore. Then dismiss the secret-scanning alert as will not fix.' },
    { t: 'Sign in, and a store with rules', status: 'next',
      why: 'deploy/firestore.rules is written: a Canadian region, nothing publicly readable, roles an admin grants, admin-only delete. Six one-time steps in a browser. Only you can do them, because the account is yours. Two limits found before building it: sign-in has to be a Google or Microsoft account, because the free plan sends five emailed links a day for the whole project, and attachments cannot go in the store at all.' },
    { t: 'What counts as a finished assessment', status: 'next', tier: 'level2',
      why: 'Answered on 21 September, and the answer is to leave it alone: Dan and Mariia agreed it stays the submitter\u2019s judgement until real submissions exist, because answering every question is not the same as attaching every piece of evidence and a submitter may come back to a question after adding one. The choices below are what a later answer has to pick from. You spotted this yourself: there is no obvious finishing line. Filling every score is one answer, but evidence is not mandatory and neither is the reasoning, so the tool cannot say when somebody is done without being told. What the rubric says: nothing. All 176 questions carry weight 1, none is marked required, and no question asks for evidence. So the finishing line is the instrument\u2019s decision, and these are the choices. Complete means every question in the set has a score or is marked not applicable. Whether the six overview fields count: they are not scored, but the lifecycle stage changes every score through the stage multipliers and the marking gates saving at all, so the working answer is that they count. Whether a floor is needed, since with none an assessment marked not applicable throughout is complete and unscored. Whether saying it is finished freezes the answers, or whether the submitter keeps editing and the assessor is warned. Whether an assessor may do anything with an unfinished one beyond reading it. Whether the portfolio averages should exclude unfinished ones.' },
    { t: 'The completion flow, and the notification that does not exist yet', status: 'next',
      why: 'Designed and ready to build. Saving an unfinished assessment online already asks first and says what an assessor will and will not do with it. What is left: the window that appears when the last question is filled, offering to mark it complete and tell an assessor; the mockup screen that follows, which has to say plainly that no notification is sent; the assessor screen split, with finished submissions and the statistics at the top and unfinished ones below; and the rule that an assessor can read an unfinished submission and cannot change anything in it.' },
    { t: 'Teammates and assessors on an assessment', status: 'done',
      why: 'A mockup, working the way sharing a document works: Share in the header, enter one address or paste a list, see who the assessment is shared with grouped by what they do, remove somebody in two steps. It says on every screen that no email is sent and no access is granted, and nothing on it can open a mail client. The addresses are recorded on the record, with two flat lists derived beside them for the rules that do not exist yet, so nothing needs migrating on the day they do. 23 assertions.' },
    { t: 'Saving online is one deliberate act, and then it keeps itself current', status: 'done',
      why: 'Nothing leaves the machine until you press Save online once. After that the copy at TBS is kept current a few seconds after you stop typing, with a floor between writes so one afternoon cannot spend the whole project allowance. Four guards stand on it, and the one that matters is the marking: nothing leaves the machine until you have said how your evidence is marked. Telling TBS it is ready is now a separate act that saves nothing new.' },
    { t: 'The tests run on every push, and publishing runs them too', status: 'done',
      why: 'Neither existed. A build that broke for anybody who signed in reached the live site behind 556 green assertions, because every suite built the tool with no store and the publish script never ran a test at all.' },
    { t: 'Signing in without access says so', status: 'done',
      why: 'An account nobody has added as an assessor now meets one screen naming the address, with the way back to the home page and the way to sign in as somebody else. Before this it reached the assessor screen and was told the pool was empty, which reads as a lost submission.' },
    { t: 'The back button works on every screen', status: 'done',
      why: 'One hash router. The assessor view, the admin view, results, settings and any questionnaire section are all addresses somebody can send, and Back walks them in the order they were visited. Before this, Back worked inside the questionnaire only, so leaving the results page went two stops back into the questions and an assessor pressing Back was dropped into the submitter view.' },
    { t: 'A submitter is told why a send did not go', status: 'done',
      why: 'Pressing Send it to TBS while signed out did nothing at all: no request, no error, no change to the badge, because the refusal was computed and dropped. It now says what happened, the badge turns, and the header offers a way to sign in. Two lines that told a live build there was no submit button and no store are gone as well.' },
    { t: 'Write the requirements down as they are decided', status: 'done',
      why: 'A requirements specification, 81 numbered requirements with a state and an owner each, generated from NOTES/requirements.data.mjs so ids and states cannot drift. It follows ISO/IEC/IEEE 29148:2018 with two departures named in the document, lists the open decisions at the top, and says how each requirement gets checked. Linked from Settings and published beside the backlog.' },
    { t: 'An admin deletes a record by typing the name out', status: 'done',
      why: 'Copied from GitHub repository deletion: everything that goes is listed, the exact name has to be typed, and the button stays dead until it matches. The rules allow an admin to delete and nobody else, because a prototype fills up with test data.' },
    { t: 'Not applicable counts as answered on the start page', status: 'done',
      why: 'It counted scored answers only, so the start page reported a smaller number than the page somebody had just left.' },
    { t: 'Stand up the store', status: 'later',
      why: 'The Worker is written and waiting in deploy/worker.js, and the page takes its address as a build input. What is left is a Cloudflare account, which only you can create: sign in, paste the file, bind a KV namespace, then build with EARB_ENDPOINT set. 1,000 writes a day on the free plan, no card, and no Canadian region.' },
    { t: 'Name an owner and a delete date for the prototype store', status: 'next',
      why: 'The objection to a store on a personal account is not the account. It is a store with no owner, no end date and no plan for handing it over. Written down before anybody asks, it stops being an objection. The page already says it is a prototype holding unclassified drafts.' },
    { t: 'Decide where the tool is published', status: 'next',
      why: 'canada-ca/TBS-OCIO-ESP already publishes a tool as one index.html in a folder, and you already have push access. One commit puts this at canada-ca.github.io/TBS-OCIO-ESP/earb-self-assessment/, with no new repo and no transfer. The repo is public, so Dan has to clear the 176 draft questions being visible first.' },
    { t: 'The marking question is about the evidence', status: 'done',
      why: 'The assessment is always unclassified, so asking how the assessment is marked was the wrong question. It asks for the highest marking of the artefacts the answers point at, which is what an assessor needs access to.' },
    { t: 'The banner stops printing the wrong marking', status: 'done',
      why: 'Choosing Protected A stamped PROTECTED A across an unclassified document, top, bottom and every printout. It reads UNCLASSIFIED with "evidence up to Protected A" beside it.' },
    { t: 'The email subject line is readable', status: 'done',
      why: 'It said "EARB evidence - m - [question]", with a placeholder nobody filled in. It now names what it is, the initiative and the question number, and the evidence box offers a Copy button.' },
    { t: 'The save badge says there is no online copy', status: 'done',
      why: 'She asked where to save online. There is nowhere, and the badge says so on hover, so "draft saved" cannot be read as the whole story.' },
    { t: 'A library of question sets', status: 'done',
      why: 'Sets accumulate. Settings lists every one this browser holds and marks the one in use. Adding one changes nothing on its own, and each row has a menu: preview the questions, make it active, delete it, and who added it. Deleting is two steps and refused only on the set in use and on the last remaining set.' },
    { t: 'Each submission is scored against its own question set', status: 'done',
      why: 'Twenty submissions answered against set 1 are untouched when set 2 becomes active, but the assessor page used to recompute them with whichever set was active and print a one-line notice. It now uses the set they were answered against when this browser holds it, names that set on every row, and says what it did. CSV export writes one file per set, because the columns are question ids.' },
    { t: 'An assessor screen with nothing in it says why', status: 'done',
      why: 'Three different situations, and an assessor can tell them apart: no shared store exists yet, this machine cannot reach it, or it is reachable and empty. It has a cat on it.' },
    { t: 'Sign in is one screen, and short screens keep their footer', status: 'done',
      why: 'The footer floated in the middle of any short page, the sign-in scrolled like a document, and the load-submissions card hung off the top edge.' },
    { t: 'Email subjects carry a code, and no initiative name', status: 'done',
      why: 'A sent email cannot be un-sent, so a subject line that carries the initiative name breaks the moment somebody renames the initiative. Every assessment gets a four-character reference when it is created, the subject reads "EARB evidence 7QF3, question B-Q1", and renaming costs nothing. It shows on the overview beside the name and on the assessor row.' },
    { t: 'Not applicable folds the work away and keeps it', status: 'done',
      why: 'A question with evidence on it turned into a grey slab when it was marked not applicable: the disclosure opened itself because there was something inside, and the whole apparatus dimmed. It folds, the summary says the work is kept and not counted, and unticking puts it back. Deleting somebody evidence because they ticked a box is not the tool decision to make.' },
    { t: 'The revert goes to the highest marking allowed', status: 'done',
      why: 'Saying no to a Protected C piece put the row back to unmarked. It goes to the marking chosen on the overview.' },
    { t: 'The backlog opens from Settings', status: 'done',
      why: 'A This build pane, with the tool version, the question set version, whether there is a store, and the link.' },
    { t: 'The assessor side keeps its work in the browser', status: 'done',
      why: 'Every audited score, verdict, note and history entry used to live in memory until the file was saved, so a reload took the afternoon. It autosaves the way the submitter side always has, Clear asks first, and the session comes back after a reload.' },
    { t: 'The store is one build input away', status: 'done',
      why: 'EARB_ENDPOINT sets both the address the page writes to and the one origin its security policy allows, so a build with no endpoint still cannot make a request. deploy/worker.js is the store: forty lines, free tier, browser-only setup.' },
    { t: 'A prompt when the evidence outranks the overview answer', status: 'done',
      why: 'Marking a piece of evidence higher than the answer given on the overview used to stay on screen blocking the save. It asks which of the two is wrong, and raising the overview answer does not re-open the pledge.' },
    { t: 'Every dialog closes on a click outside it', status: 'done',
      why: 'Menus stayed open until something else was clicked, and the discard window had no way out but its own buttons. Cancelling is the outcome, so a stray click can never delete. The classified pledge is the exception, because a tick is the point of it.' },
    { t: 'One dialog everywhere, and no silent yes', status: 'done',
      why: 'A browser without dialog support fell back to window.confirm, which named neither the count nor the stake and treated OK as yes. The same dialog renders in place instead, so the tests press the real buttons too.' },
    { t: 'A filled section stops looking empty', status: 'done',
      why: 'The disclosure said "Add reasoning or evidence" whether or not anything was inside. The heading is stable now and a status follows it, the way a government task list marks a section as started.' },
    { t: 'Done asks the reader to finish, and says what is missing', status: 'done',
      why: 'Pressing Done on the overview with something empty repainted the same card and explained nothing. It goes to the gap and names it, and what is left is listed under the step at all times.' },
    { t: 'The cat had horns, and then its mouth crossed its body', status: 'done',
      why: 'First the head outline peaked at both sides, which were the ears, and two more thin triangles were drawn floating above them. Then the mouth arc sat on the body top edge and the two curves read as one line. Ears joined to a round head, face eight units clear of the body.' },
    { t: 'A classified file cannot be left attached', status: 'done',
      why: 'Hiding the attach control was not enough: attach while the row is unclassified, raise the marking afterwards, and the file stayed, saved, and passed every check. The save is blocked now and the row says why, which is the one promise the pledge window makes.' },
    { t: 'The email note is a field, and keeps the line that was sent', status: 'done',
      why: 'It was a prefix on the location text, so editing that text by hand changed the state, and renaming the initiative made the recorded subject and the shown subject disagree. There is also a way to take the note back.' },
    { t: 'The empty evidence row stops blocking the save', status: 'done',
      why: 'Add evidence created a row with no marking, and the save gate demanded one immediately. An empty row is nothing to mark. A classified row no longer offers attaching at all, and a row already recorded as emailed does not offer it either.' },
    { t: 'Question ids lose a letter', status: 'done',
      why: 'BU-Q1 is now B-Q1. The four domain initials are distinct, so the second letter carried nothing. Cheap today because no real submission exists; expensive once ids are column names in somebody exported spreadsheet.' },
    { t: 'Nothing is destroyed in one step', status: 'done',
      why: 'An audit found twenty destructive actions and eleven of them destroyed something with no prompt at all. Every one now asks, keeps a copy where it can, or leaves the work alone.' },
    { t: 'Not applicable hides the scale and keeps the score', status: 'done',
      why: 'The eleven descriptions explain a score, and a question that does not apply has none. Ticking the box also used to erase the score, and unticking did not give it back.' },
    { t: 'The frame stops reading as part of the page', status: 'done',
      why: 'Measured: the header separated from the page by 1.13 to 1 in light and 1.08 to 1 in dark, and the page footer was exactly the page colour. The frame has its own edge token, the dark frame is now lighter than the page, the footer has a ground, and a shadow appears only once content scrolls under it.' },
    { t: 'The rail stops repeating the domain tabs on a narrow screen', status: 'done',
      why: 'Below 860px the rail lies down into a strip under the tabs. On the overview it had no section rows to show, so the same five items appeared twice. Found while checking the marking banner on the live page.' },
    { t: 'The prose linter takes any file', status: 'done',
      why: 'The writing rules were being applied from memory for chat replies, and em dashes went out. Replies go through the same linter as the app copy now.' },
    { t: 'Backlog gets jump links and a Done section that stays', status: 'done',
      why: 'Done was at the bottom of eight layers with no way to reach it. Every section now has a link at the top, and Done is split into what came after Dan’s review and what he had already seen.' },
    { t: 'Every backlog item carries its reason', status: 'done',
      why: 'Five items had a title and nothing else, so they read as jargon. All of them now say why they exist.' },
    { t: 'Rail’s Overview row shows a count and a bar', status: 'done',
      why: 'Every other rail row had both; Overview had neither, which reads as a row stuck at zero.' },
    { t: 'Overview bar moves on the first keystroke', status: 'done',
      why: 'It counted the three groups, and group one needs four fields. It now measures the six fields while the count still reads in groups.' },
    { t: 'README and Settings stop describing a local-only tool', status: 'done',
      why: 'Both said the tool cannot transmit and that the repo is private, and neither was true.' },
    { t: 'Settings marks the unbuilt parts as unbuilt', status: 'done',
      why: 'It promised a submit act and a withdrawal path as though both existed. Neither is written, and copy that describes a feature has to say whether the feature is there.' },
  ],
};

export const layers = [
  {
    title: 'Known problems', owner: 'Build team',
    groups: [
      { t: 'The submitter page and the assessor page share one browser', status: 'next',
        why: 'Found while working out why the demonstration page was showing real work. The demonstration has its own names now. The two real pages still share every name with each other, because they are one origin, and one of them acts on it: activating a question set on the assessor side clears the submitter\u2019s draft in the same browser, with no warning and nothing to undo it. Nobody has hit this, because the two sides are usually different people. They are the same person on one laptop whenever anybody tests.' },
      { t: 'Discarding a draft says the browser is holding nothing, and it is', status: 'next',
        why: 'Also found in that sweep. Every assessment this browser has ever saved online leaves a full copy behind under its own name, and nothing in the tool ever removes one. The window that discards a draft says what it is taking away and that copy is not in the list, so the sentence is untrue in the one place somebody reads it to decide.' },
      { t: 'The assessor screen was on the wrong spacing ratio', status: 'done',
        why: 'Measured: a card padded 1.05rem inside and margined .85rem below, so two unrelated blocks were 3.2px CLOSER together than a heading was to its own content. A ratio of 0.81 where the submitter\u2019s results page runs 2.76. Every complaint about buttons crowding text came from that one inversion, plus .actions carrying no top margin at all, so its gap was whatever the element above happened to leave: zero after a table and zero after every heading. On the list screen the export button\u2019s own border was touching the table\u2019s closing rule while being 8px from the button beside it, so a control was closer to content it had nothing to do with than to its own group. On the detail screen 180 audit rows stacked at 0px apart, separated only by the hairline this stylesheet had already measured as too faint to read as a boundary, and 51 pairs of tinted rows touched and merged into one band.' },
      { t: 'Clear is gone from the assessor toolbar', status: 'done',
        why: 'It emptied every submission and every score, verdict and reason the assessor had typed. The audit exists in one browser key and in a file somebody may or may not have saved, so it was the only copy: a control that destroyed an afternoon, on the main screen, the same size and colour as an export beside it. Closing one submission you are finished with is what an assessor actually wants and the screen could not do, so that is a per-row menu item now, and the one that closes everything is the last item of a menu in red with an offer to save the audited files first. No test covered the old button, which is how it lasted.' },
      { t: 'The assessor\u2019s audit never reaches the store', status: 'next',
        why: 'The biggest one. An assessor scores a submission and the only thing that happens is a file downloads to their laptop. So the portfolio\u2019s audited count can never leave zero, and a review exists nowhere the department can see. It is a decision before it is a patch: the published rules describe the audit as a separate document beside the assessment, so an assessor can write a score without being able to touch an answer, and the code keeps it as a field inside the assessment, which the rules refuse to let an assessor write at all. One of the two has to move. Writing it where the rules already allow means a second small write beside the assessment; keeping it as a field means widening the rules so an assessor may update the document, and then something has to stop them editing answers.' },
      { t: 'Nothing tests the sign-in round trip', status: 'next',
        why: 'Every test seeds a session by hand, so the three legs of a real sign-in are untested: asking Google for an address to send somebody to, holding the reference while the browser is away, and trading the code that comes back for a token. That is the one leg that reached you broken, twice.' },
      { t: 'The rules are only ever tested signed out', status: 'next',
        why: 'deploy/check-rules.sh makes four calls with no account and asserts all four are refused, which is worth having. What nothing covers is the part that matters once there are two departments in the store: that one submitter cannot read another\u2019s assessment. Proving that needs two signed-in identities, which means the Firebase emulator and its rules-testing library, run from the tests.' },
      { t: 'The question-set lock only warns, and its own importer overwrites it', status: 'next',
        why: 'rubric/rubric-ids.lock.json records what each of Dan\u2019s 176 question ids meant, so that a question changing meaning while keeping its id can be caught. Every assessment records the ids it answered, so a changed meaning makes old scores wrong without anything looking wrong. The lock only prints a warning, it is not part of npm test, and the importer rewrites it at the end of its own run, so a drift is absorbed after one pass. Reading it in the tests and failing on a changed meaning is half an hour.' },
      { t: 'A submitter cannot remove their own record', status: 'wait',
        why: 'Yours to decide, and parked until you do. Discarding a draft leaves the copy at TBS untouched, because delete is admin-only. The screens say so. The alternative is one line in the rules letting an owner delete a record nobody has been asked to review yet.' },
    ],
  },
  {
    title: 'In your name', owner: 'Mariia',
    groups: [
      { t: 'GitHub, myermcat', status: 'next',
        why: 'Two repositories, both yours. The objection to a personal account is never the account: it is one with no owner of record and no plan for handing it over.',
        subs: [
          { t: 'myermcat/tbs-earb-self-assessment', status: 'next',
            why: 'Private, and it holds the source with every commit authored by you. It moves to canada-ca when Nick answers.' },
          { t: 'myermcat/tbs-earb-self-assessment-preview', status: 'next',
            why: 'Public, and it holds the built page, the backlog and the requirements. Retire it once the tool is published from canada-ca.' },
        ] },
      { t: 'Firebase project tbs-earb-self-assessment', status: 'next',
        why: 'Live since 1 September. Firestore in Montreal, the rules published, Google sign-in on, you as the first admin. Free plan, no card. Three things a reviewer asks for are still unwritten.',
        subs: [
          { t: 'Name an owner of record', status: 'next',
            why: 'You, in writing, until somebody at TBS takes it. This is the sentence that answers the question before it is asked.' },
          { t: 'Set a date it gets deleted', status: 'next',
            why: 'The end of the co-op term is the obvious one. An unowned store with no end date is what gets a prototype refused.' },
          { t: 'Write down how it hands over', status: 'next',
            why: 'At 40 KB times a few hundred, the whole store moves to a team-owned account in an afternoon. Saying so in advance turns the objection into an answered question.' },
          { t: 'Restrict the browser key to your site and to three APIs', status: 'next',
            why: 'GitHub flagged the Firebase web key in the published page as a Google API key. It is a public identifier by design and it authorises nothing on its own, so the page is not a leak. What is worth changing is that the key currently answers from anywhere: a check from the command line reached the project with no site attached at all. In the Google Cloud console, under Credentials, the browser key takes a website restriction of myermcat.github.io and localhost, and an API restriction of Identity Toolkit, Token Service and Cloud Firestore. Nothing the tool does falls outside those three.' },
          { t: 'Close the GitHub alert as will not fix', status: 'next',
            why: 'The alert is correct about what it found. Revoking the key would take the store down and change nothing about who can read what, because reading is gated by sign-in and by the published rules. Will not fix, with the restriction above as the note.' },
        ] },
      { t: 'Nothing else is in your name', status: 'done',
        why: 'No Cloudflare account was created, no domain was bought, no paid service is attached to anything. The tool itself is one HTML file and needs no account to run.' },
    ],
  },
  {
    title: 'Question set', owner: 'Dan',
    groups: [
      { t: 'Whether a department says how many decisions are already made', status: 'wait', owes: 'Dan', tier: 'level2',
        why: 'Dan floated this on 21 September as a way to tell whether an assessment can still change anything. A department that has chosen the product and signed the contract answers the same 176 questions as one still deciding, and the two are worth different amounts to a board. It would be one overview field and nothing scored.' },
      { t: 'Answer types and criticality', status: 'wait',
        why: 'The shape of the questions, which Dan called the biggest remaining piece. Our reading is in the tool and labelled provisional.',
        subs: [
          { t: 'Confirm the answer type for every question', status: 'wait',
            why: 'Ten are yes/no on our reading of the wording. The other 166 are scored 0 to 10.' },
          { t: 'Confirm which no answers matter most', status: 'wait',
            why: 'Every no colours its section red today. If some should not, that is his call.' },
          { t: 'Set per-question criticality', status: 'wait',
            why: 'Separate from section weight, and nothing in his workbook carries it.' },
        ] },
      { t: 'Content still owed', status: 'wait',
        why: 'None of this is ours to write.',
        subs: [
          { t: 'Fix the section weights that total 80', status: 'wait',
            why: 'His error, confirmed in his own words. The tool shares the missing 20 proportionally and shows the normalised share.' },
          { t: 'Add security and privacy questions', status: 'later',
            why: 'Neither is represented. A security review is already asking. The topic view makes the gap visible in the meantime.' },
          { t: 'Bring in the dropdown answers', status: 'wait',
            why: 'No picklists exist. Needs the 700 or more past assessments, which only he can hand over.' },
        ] },
    ],
  },
  {
    title: 'Engine', owner: 'ours',
    groups: [
      { t: 'The routing thresholds are approximations, and Dan said so', status: 'wait', owes: 'Dan', tier: 'level2',
        why: 'Confirmed on 21 September: the numbers the tool routes on are the ones he named in the first conversation and are not accurate. He added a case the tool cannot express. A department scoring itself around three does not need to come to the board at all, because everybody already agrees the work is weak, and what matters is what they plan to do about it. So the band is not one line with a score on each side of it.' },
      { t: 'Recording the rework loop', status: 'later', tier: 'level2',
        why: 'Dan called the back and forth before a board date the real value GC EARB adds, and said on 21 September that he cannot prove that value because nothing captures it. It is also why the endorsement rate is 100 per cent: an initiative that would fail is reworked or abandoned before it ever reaches the board. Recording each round would make it visible. What a round looks like as data is the open question, and nobody has answered it.' },
      { t: 'Question mechanics', status: 'done',
        why: 'What the instrument can carry.',
        subs: [
          { t: 'Multiple answer types', status: 'done',
            why: 'A type field with scale as the default, so nothing existing breaks.' },
          { t: 'A no answer colours its section', status: 'done',
            why: 'The question, its section, its rail row and its domain tab, and it stops nothing.' },
          { t: 'Topic metadata and per-topic roll-up', status: 'done',
            why: 'Security, privacy, cost, data, business and technology, visible without inventing a fifth domain.' },
          { t: 'Two-topic scoring', status: 'done',
            why: 'Once in the overall, at full weight inside each topic, because the weight genuinely differs by topic.' },
        ] },
      { t: 'Storage and concurrency', status: 'next',
        why: 'Everything is unclassified, so it can all live online. The seam is written; the store is not.',
        subs: [
          { t: 'The store seam', status: 'done',
            why: 'src/store.ts. One constant from live, and the dashboard already reads through it.' },
          { t: 'The three calls a real write needs', status: 'done',
            why: 'Saving, saved, failed with a reason. Nothing drives them yet, so the wording is settled before the write exists.' },
          { t: 'One deliberate first submit', status: 'next',
            why: 'You should know the moment your work becomes visible to TBS.' },
          { t: 'Autosave online after that', status: 'next',
            why: 'Like a document. Every later change writes through.' },
          { t: 'Field-level last write wins, with a marker', status: 'next',
            why: 'Not locking. Two people in different questions never collide.' },
          { t: 'Tell the other person it changed under them', status: 'next',
            why: 'The audit trail already keeps both accounts. What is missing is the live signal while somebody is looking at the line.' },
          { t: 'Submitter answers and assessor scores are separate fields', status: 'done', seen: true,
            why: 'Which is why a submitter and an assessor cannot collide at all.' },
        ] },
    ],
  },
  {
    title: 'Interface: the submitter', owner: 'ours',
    groups: [
      { t: 'The questionnaire on a phone', status: 'done',
        why: 'Measured at 375 by 812, before and after. The page laid out 601px wide and every question card was cut off at the right edge; it is 375 now. The fixed header was 322px and the bar at the bottom 191px against an 812px screen, so the question itself had 299px, and it has 500.9, which is the first time a whole question card fits. The section rail rendered as a row of bare counts because every label collapsed to zero width, and it names its sections again. Four captions in the bar were bare English inside a bilingual tool. No new breakpoint was added and a gate refuses an eighth, because seven narrow widths were already in the file and none of them was the agreed one. Desktop measured unchanged at 1200 by 900. Nobody has said they are filling this in on a phone, and nobody has said they are not.' },
      { t: 'Every readout agrees with the page under a category lens', status: 'done',
        why: 'Reported as: with Security on, the rail still shows 0 of 9 for a section showing 2 questions. Three places counted the same questions and only the domain tabs knew a lens was on. One function counts now and every readout calls it, so with Security on and Business open the tab, the rail row and the bar at the bottom all say 0 of 1 against the one question on the page, the four tabs add up to 25, and that is what the chip and the second bar say. Nothing exercised the lens at all, which is how it shipped; the gate asserts that the readouts agree with the questions rendered rather than pinning any figure, because the figures are Dan\u2019s to change.' },
      { t: 'Evidence', status: 'done',
        why: 'The change that follows from unclassified-only.',
        subs: [
          { t: 'Ask for a link', status: 'done',
            why: 'Point at where it lives, and make sure your assessor can open it.' },
          { t: 'Email fallback, with a pattern', status: 'done',
            why: 'Marking, sent by email, subject line written for you, so an assessor can find it.' },
        ] },
      { t: 'The classified pledge, as a modal', status: 'done',
        why: 'She chose Protected A on the strip that says "mark this file to save it" and nothing happened. The advice panel was on a different screen, so it could be scrolled past and was.',
        subs: [
          { t: 'Any marking above unclassified takes over the screen', status: 'done',
            why: 'Whichever control set it. The strip, the picker, and anything added later go through one function, so they cannot drift apart again.' },
          { t: 'The close control is dead until the box is ticked', status: 'done',
            why: 'Grey and unclickable, and it says "tick the box first". Escape does not dismiss it and clicking outside does nothing.' },
          { t: 'The way out changes the answer', status: 'done',
            why: 'An accidental click needs an exit that is not a dismissal: "this is unclassified after all" changes the answer, and the warning stands.' },
          { t: 'It asks once per marking', status: 'done',
            why: 'After the pledge, switching between classified markings does not ask again. The panel on the overview stays as the reference.' },
          { t: 'The unmarked banner opens the marking question', status: 'done',
            why: 'It scrolled to an element that only exists on the overview, so from any of the twenty question pages it did nothing at all.' },
        ] },
      { t: 'Marking', status: 'next',
        why: 'Somebody still has to state the marking of what they point at.',
        subs: [
          { t: 'One big unclassified tile, the six grouped behind it', status: 'done',
            why: 'The default must not be taxed by the rare path.' },
          { t: 'Classified panel with an acknowledgement toggle', status: 'done',
            why: 'What to do instead, at the moment it is relevant.' },
          { t: 'Collapse three pickers into one', status: 'next',
            why: 'The footer’s seven pills bypass the whole design.' },
        ] },
      { t: 'Submitting', status: 'next',
        why: 'The moment work stops being private. Everything here is about the person knowing that.',
        subs: [
          { t: 'First-submit confirmation', status: 'next',
            why: 'Names what is about to go online and asks them to confirm it is unclassified.' },
          { t: 'Save status indicator', status: 'done',
            why: 'Draft in browser, saving, saved, or not saved with a reason. It is in the header now, so it is on every screen and on a phone; it was on the 21 question pages only, and CSS hid it below 720px.' },
          { t: 'Silent until something is actually written', status: 'done',
            why: 'It opened at "draft saved in browser" on an empty page, which is a claim ahead of the fact.' },
          { t: 'One live indicator for the whole visit', status: 'done',
            why: 'Each repaint added another listener holding a dead node. Harmless while the state never changed, and a leak the moment writes start.' },
        ] },
    ],
  },
  {
    title: 'Interface: the assessor', owner: 'ours',
    groups: [
      { t: 'Identity', status: 'wait',
        why: 'Their name goes against a number somebody may dispute.',
        subs: [
          { t: 'Mockup verification screen', status: 'done',
            why: 'Labelled a mockup, the departmental-account button visibly disabled, everything unverified.' },
          { t: 'Real sign-in', status: 'wait', owes: 'Dan',
            why: 'Blocked on how identity gets checked at all, which is his answer to give.' },
        ] },
      { t: 'Nothing an assessor typed is overwritten silently', status: 'done',
        why: 'Four places did it. Agree-with-all replaced a verdict somebody had already given, the note field rewrote the reason on whatever change was last in the trail, reloading a file of the same name discarded the audit attached to it without a word, and the email button wrote over a link somebody had typed.' },
      { t: 'Auditing rules Dan gave as rules', status: 'done',
        why: 'He stated all five as requirements in the review, and all five are built.',
        subs: [
          { t: 'Justification required on a changed score', status: 'done',
            why: 'His rule. The file cannot be saved while one is missing, and the button says how many are outstanding.' },
          { t: 'Accept-all per section', status: 'done',
            why: 'He asked for it by name. It touches no score, and skips any changed score that still needs a reason.' },
          { t: 'Assessor recorded per question', status: 'done',
            why: 'Two assessors on one high-profile file. Each change carries a name, a time and a reason.' },
          { t: 'The edit exchange, visible', status: 'done',
            why: 'The line says it was edited and by whom. The full back and forth opens on request, and nothing is overwritten.' },
          { t: 'Evidence read-only', status: 'done',
            why: 'Already true, and now held true by a test.' },
        ] },
      { t: 'Load a question set moves here', status: 'done',
        why: 'It belongs to whoever maintains the instrument. A submitter is told where it lives and not handed the control.' },
    ],
  },
  {
    title: 'Interface: admin', owner: 'ours',
    groups: [
      { t: 'Reachable without going through the assessor view', status: 'done',
        why: 'It sat behind two clicks on the assessor side with nothing on the start page pointing at it. There is a line under the assessor link now, and it asks who you are the same way.' },
      { t: 'The portfolio dashboard', status: 'done',
        why: 'Dan’s self-updating dashboard. It recalculates every record from the answers as the page draws, so there is no stored number to go stale.',
        subs: [
          { t: 'Averages by domain and by topic', status: 'done',
            why: 'The topic cut is the one a single assessment cannot show: security spread thin over four domains looks fine in each of them.' },
          { t: 'Every record, weakest first', status: 'done',
            why: 'The list is a worklist. Red rows are the ones with a no answer.' },
          { t: 'Portfolio CSV', status: 'done',
            why: 'One row per record, topic columns included.' },
          { t: 'It says what it can currently see', status: 'done',
            why: 'With no store, that is this browser and the files opened this session. The page says so, so it cannot be read as live.' },
        ] },
      { t: 'Admin-only actions', status: 'wait', owes: 'Dan',
        why: 'Nobody has decided whether admin is a role. Listed so the roles matrix is complete.',
        subs: [
          { t: 'Withdraw a record', status: 'later',
            why: 'Out of every statistic and still in the list, with nothing deleted.' },
          { t: 'Re-assign an assessor', status: 'later',
            why: 'Somebody leaves, or a file needs a second pair of eyes.' },
          { t: 'Clear out test submissions', status: 'later',
            why: 'Dan raised it and parked it.' },
        ] },
    ],
  },
  {
    title: 'Interface: the executive view', owner: 'ours',
    groups: [
      { t: 'Dan’s twelve-month questions', status: 'later',
        why: 'The reason the data is worth capturing at all. All of it needs more than one record to mean anything.',
        subs: [
          { t: 'Per-question averages and histograms', status: 'later',
            why: 'Which questions the whole GC is weak on, which is the argument for changing a question.' },
          { t: 'Average by department', status: 'later',
            why: 'Needs enough records that a department average is not one initiative.' },
          { t: 'Best and worst evidence per question', status: 'later',
            why: 'Gives a submitter an example of what good looks like, which is the thing people ask for first.' },
        ] },
    ],
  },
  {
    title: 'Data and hosting', owner: 'ours and TBS',
    groups: [
      { t: 'How an assessor proves who they are', status: 'next',
        why: 'Four routes, and they are not alternatives so much as a sequence. Written down together because each one was being argued on its own and the cheapest was never costed.',
        subs: [
          { t: 'A sign-in link sent to a work address', status: 'next', owes: 'Mariia',
            why: 'Built on 23 September and waiting on one console step. It is under Other ways to sign in, below the Google button, which is where every product that offers this puts it. Firebase mails a one-time link, opening it proves the person can read that mailbox, and the address comes back verified, which is what the store\u2019s rules insist on. The step nobody else can do: Firebase console, Authentication, Sign-in method, enable Email/Password and then Email link (passwordless sign-in) under it. Until that is done the screen says so in those words instead of printing the service\u2019s error code. What it costs: five sign-in emails a day for the whole project on the no-cost plan. Google\u2019s own note on that row names the remedy, which is to attach a billing instrument, and the columns of that table are headed instrumentless and with billing instrument, so the gate opens on a card and not on spending. THE CARD IS NOT THE RIGHT ANSWER HERE AND AN EARLIER VERSION OF THIS SAID IT WAS. Firebase\u2019s spend caps cover four services and neither Firestore nor Authentication is one of them, budget alerts tell you after money has gone, and this store carries a rule allowing anybody who names a document to read it and anybody at all to create one. A card on a co-op student\u2019s personal account, over a store with an open create path, removes the only ceiling the project has. Keep it on the no-cost plan. Three assessors over a whole fall term is about six sends, because a laptop that signs in stays signed in and a device costs one link in its lifetime. Revisit if a real working day is ever lost, and write down the date it happened. Read the five carefully, because it is easy to read as five people. It is five sign-in events a day across the whole project, and a refresh token does not expire, so somebody who signs in once stays signed in until they clear their browser. What it will not survive is a room trying it at the same time, or one person mistyping an address twice: the sixth send that day is refused and there is no way onward. There is a second way past it that needs no card and nobody outside this team, and it was missed the first time because only one row of the table was read. The same table gives address verification mail a thousand a day and password resets a hundred and fifty, against the link\u2019s five. So an enrolment where somebody sets a password and verifies the address runs at two hundred times the cap on the same plan, and it satisfies the store\u2019s rules for the same reason the link does, because the verification mail is the verification. What it costs is that people then have a password, which this tool has been built to avoid. That is a decision and it has not been made. One thing worth knowing for later: the cap of five is Firebase putting mail in the post, and generating a link is a separate limit of 20,000 a day, so a route that generates the link and hands it to another mailer is governed by the larger number. GC Notify is the sanctioned service in the Government of Canada and has a REST interface and no SMTP, which is what makes that a piece of work and not a setting. One worry checked and closed on 24 September: the Firebase console warns that Dynamic Links shutting down takes email link authentication with it, which would be this feature. It does not reach us. Firebase\u2019s own answer is that the deprecation affects handling incoming URLs on mobile devices, meaning an application that intercepts a link, and a page opened in a browser is untouched. The date was 25 August 2025, over a year past, and the flow works today, so the question is settled by the thing working and not by the sentence alone. Custom SMTP is also configurable from this console on the no-cost plan, which an earlier note said needed an upgrade to Identity Platform. It is the likeliest fix for a link that never reaches a gc.ca address, because what leaves today comes from noreply at a firebaseapp.com address with no sender name.' },
          { t: 'Microsoft sign-in, and what is actually blocking it', status: 'next', tier: 'level2',
            why: 'The final goal, and the blocker is a measurement nobody has taken rather than a decision from TBS. Three things settled on 24 September. One, registration needs nobody\u2019s advance permission: an application registered once as multi-tenant lets people from any Microsoft directory sign in, the other organisation is never asked beforehand, and it costs nothing. The September note saying TBS must register it was wrong about that. Two, what is true is narrower and it is ours: the store refuses any identity without a verified address, and Firebase has an open report since August 2024 that it reports a Microsoft address as unverified. Three, and this is the part that changes the answer, that report is about an address signing in for the first time, where Microsoft creates the account. An address that has already signed in once by emailed link already exists with a verified address, and Firebase with one account per address does not make a second. The link shipped first, so that is the case our three assessors will actually meet. Nobody has measured either case. Measuring costs an application registration in any directory somebody already has, which Entra lets an ordinary user make by default, and then one real sign-in with the token read back. If the answer is that the address comes back verified, the build is a button, a provider enabled in the console and two redirect addresses. If it comes back unverified, the choice is between asking TBS for a single-tenant registration, which keeps the rules intact because TBS controls the addresses, and softening the rule, which would mean trusting every directory administrator in the world with a claim they are free to set, over a store holding pre-decisional departmental work. Do not soften the rule.' },
          { t: 'Find out what corporate IT Security has already assessed', status: 'wait', owes: 'Nick, then whoever owns the list', tier: 'level2',
            why: 'The question under the other three, and nobody has asked it. Nick said what they would prefer depends on what IT Security has assessed, and that this is corporate and not his group. The useful ask is for the list of assessed services, because the list decides the destination, where a ruling on Firestore only closes a door. He named Robin Sidhu for the identity side and was explicit that it is a separate conversation from which third-party services are authorised. Asking IMTD for an Azure registration before this is a request that fails twice. Commitment: none, it is one message.' },
          { t: 'Priced the stores, and the answer is to keep Firestore', status: 'done',
            why: 'Asked on 23 September: how much would it cost if paid, is there anything free, why are we on Firestore at all. Three answers. The bill is nothing and would stay nothing: Firestore in Montreal is 3.3 cents per hundred thousand reads past a free fifty thousand a day, and this tool would need three million reads in one day to be charged one cent. Pay-as-you-go carries the same free amounts, so the only thing a card changes is the mail quota. Nothing is cheaper, because nothing is cheaper than nothing, and the free tiers elsewhere carry traps this tool would hit: a Supabase project on the free plan is paused after a week of no traffic, which is exactly what a tool used before a board meeting looks like, and its own sign-in mail is capped at two an hour. Appwrite has no Canadian region. Corrected on 24 September: this entry used to say the access code could not survive the move, and that was wrong. It was tested against a real Postgres rather than argued about. A code is a twelve-character string; it is a document name today and would be a primary key tomorrow, and nothing anybody holds carries it in a link, so every code keeps working. The mechanism survives too: a policy of the form USING (id = the code arriving as a request header) gives a holder exactly their own row and gives somebody with no code nothing, including through a count. Twenty assertions, all passing. What does not survive is the simplicity. The four comparisons that stop a code holder moving a record into somebody else\u2019s account become a trigger function, and everything in a Supabase public schema is reachable by the anonymous key until it is given a policy of its own, where a Firestore path with no rule is closed. The reason to stay is simpler and it is about this tool\u2019s rhythm: a free Supabase project is paused after a week without traffic, and this tool goes quiet for months between assessment rounds, so the first assessor back would meet a sleeping database and a dashboard they have no account on.' },
          { t: 'Moving the store off Firestore', status: 'later', tier: 'level2',
            why: 'Rewritten on 23 September because the first version of this was not understandable. What it means: today the page talks straight to Google\u2019s database and Google decides who may read what. Moving off Firestore means putting something of our own in the middle, and then we decide, which means we are the thing that has to be right, stay up and stay patched after the work term ends. Today a bad request is refused even if somebody edits the page\u2019s JavaScript in their own browser. Three to five weeks for a destination somebody has named, and no estimate for one nobody has: only three files anywhere name Firestore, but the tidy seam covers the submitter\u2019s document alone and eleven modules reach past it for roles, sign-in, withdrawal and the code lookup, so those get untangled first. And it does not fix the reason an assessor needs an account. Show me every submission cannot be tied to a secret somebody is holding; a server has the same problem, because it still has to know who is asking. What it would genuinely buy is limiting how often one address can ask, a log of who asked for what, and whatever the IT Security list turns out to say. Real, and none of it urgent.' },
        ] },
      { t: 'What corporate credentials cost', status: 'wait', owes: 'Dan', tier: 'level2',
        why: 'Dan wants departmental accounts eventually and does not know what linking them costs. He put it in October, after the prototype stage. What is already known: registering an application in Azure AD costs nothing, and Firebase carries the Microsoft provider to 50,000 monthly users on the free tier, so price is not the obstacle. The obstacle is that IMTD has to register the application, and Nick reads the chance of them agreeing as low.' },
      { t: 'Get into canada-ca', status: 'next',
        why: 'Access is done. Publishing is a commit away in a repo you can already push to. A repo of our own is a separate, slower question.',
        subs: [
          { t: 'Publish into canada-ca/TBS-OCIO-ESP', status: 'next',
            why: 'One folder holding one index.html, the same shape as earb-forward-agenda, which that repo already serves. Needs Dan to clear the questions being public.' },
          { t: 'GitHub Pages cannot serve a private repo on a free account', status: 'done',
            why: 'Checked: all 35 Pages sites in canada-ca come from public repos, and no private repo there serves one. This is why a separate public preview repo exists.' },
          { t: 'Reply to Nick: transfer the existing repo', status: 'done',
            why: 'Sent. 28 commits of history, all yours.' },
          { t: 'Nick’s answer on who performs the transfer', status: 'wait', owes: 'Nick',
            why: 'Open an issue on canada-ca/welcome is the route he named. Whether he moves it or you do is the part still unanswered.' },
          { t: 'Retire the separate preview repo', status: 'next',
            why: 'Pages can come from the canada-ca repo once it exists.' },
        ] },
      { t: 'Where submissions arrive', status: 'next',
        why: 'Dan asked us to figure it out. GitHub Pages serves static files and cannot accept a write, so something has to receive one.',
        subs: [
          { t: 'A write endpoint', status: 'next',
            why: 'An Azure Function is the cheapest route: canada-ca/TBS-OCIO-ESP already builds through Azure Pipelines, so the account and the approval path exist.' },
          { t: 'Open the CSP to exactly that origin', status: 'next',
            why: 'One line in build.mjs. The page blocks every outbound request until then.' },
          { t: 'Per-user auth', status: 'later',
            why: 'The known limit. Microsoft Entra is the obvious route, since departments already sign in with it.' },
        ] },
      { t: 'Notifications', status: 'wait',
        why: 'GC Notify is the sanctioned service and is already in Dan’s own rubric at application question Q33. What triggers one is his decision and he has not made it.',
        subs: [
          { t: 'Draft the email', status: 'done', seen: true,
            why: 'Opens the person’s own mail client with the message written. All a static page can do.' },
          { t: 'Decide the triggers', status: 'wait', owes: 'Dan',
            why: 'Submission, assignment, a changed score and a reminder are four different decisions.' },
        ] },
    ],
  },
  {
    title: 'Process, for people', owner: 'Dan and John',
    groups: [
      { t: 'How John’s team validates evidence', status: 'later',
        why: 'Their job changes completely and Dan expects resistance.' },
      { t: 'What the intake accepts, and from whom', status: 'later',
        why: 'Dan called it a protocol for the humans.' },
      { t: 'Which initiatives must submit', status: 'later',
        why: 'His call. Blocks nothing we build.' },
    ],
  },
];

export const resolved = [
  { q: 'Can the assessor side work on a code, the way the submitter side does?',
    a: 'No, and it was worked through rather than waved away. The legal half is real: a rule can grant read on a named document, so a roll-up document named by a long code would be a lawful thing to read, and each submitter could be confined to writing their own row into it. It fails on what a leak costs. One assessment code leaks one assessment. An index code leaks every department at once, and it cannot be rotated, because its address is compiled into every published submitter page: old pages keep writing to the old document and anybody holding an old build keeps the address. Loosening the write rules enough to make it work also removes the one thing that lets a reader tell afterwards whether a verdict was written by an assessor or by the department being assessed, which takes the audit out of evidence.' },
  { q: 'Should the tool hold classified information?',
    a: 'No. Nothing protected or classified goes in at all, settled with Dan on 1 September. That removed the second deployment, the local-only engine, the theme switch, and the whole recall problem.' },
  { q: 'What happens to online data when a marking rises?',
    a: 'Dropped. The tool never stores classified evidence, so the question cannot arise.' },
  { q: 'Does a two-topic question count twice overall?',
    a: 'No. Once in the overall score, and at full weight inside each topic, which is where the weights genuinely differ.' },
  { q: 'File sharing for a team filling one in together?',
    a: 'No files. Everything is online, so version control stops being a problem the tool has to solve.' },
  { q: 'Deletion rights',
    a: 'Nothing is ever hard-deleted. A record is withdrawn and left out of the statistics.' },
  { q: 'One build or two?',
    a: 'One. Submission is a capability the hosting turns on.' },
  { q: 'Where the plan lives',
    a: 'This page. The Markdown version is deleted.' },
  { q: 'Org access to canada-ca',
    a: 'Done. Nick invited you, and the TBS-OCIO-ESP team gives push access to canada-ca/TBS-OCIO-ESP.' },
  { q: 'Who may replace the question set?',
    a: 'The assessor and admin side only. Loading one clears every answer, so a submitter is told where it lives and not handed the control.' },
  { q: 'How does the dashboard stay current?',
    a: 'By storing nothing. It recalculates each record from its answers as the page draws, so there is no roll-up that can go stale.' },
];

export const questions = [
  { q: 'What an assessor sees of the pool', who: 'Dan or Chris',
    blocks: 'Filtering, and any My assessments view', meanwhile: 'Every assessor sees everything' },
  { q: 'Who may write to the prototype store', who: 'ours, then Dan',
    blocks: 'Nothing yet', meanwhile: 'Anybody who reads the page source. Fine for unclassified drafts, and the reason the real one needs the departmental sign-in' },
  { q: 'Can the 176 draft questions be public', who: 'Dan',
    blocks: 'Publishing inside canada-ca', meanwhile: 'The preview is on a personal public repo, which is the same exposure with less visibility' },
  { q: 'Who may edit a stored assessment, and how it is checked', who: 'Dan',
    blocks: 'Real authentication', meanwhile: 'Mockup screen, everything labelled unverified' },
  { q: 'Verifying an assessor’s identity', who: 'Dan',
    blocks: 'Real sign-in', meanwhile: 'Typed name, labelled unverified on every change it records' },
  { q: 'Is admin a role, or an assessor with more buttons?', who: 'Dan',
    blocks: 'The admin-only actions', meanwhile: 'The dashboard is built; the actions are listed and marked unbuilt' },
  { q: 'Notification triggers and recipients', who: 'Dan',
    blocks: 'Notifications', meanwhile: 'Draft the email. GC Notify is the sanctioned route' },
  { q: 'Which questions are yes/no, and which no answers matter most', who: 'Dan',
    blocks: 'Nothing', meanwhile: 'Ten on our reading, labelled provisional in the app' },
  { q: 'The routing thresholds', who: 'Dan',
    blocks: 'Nothing', meanwhile: 'Interpolated between two numbers he named, labelled provisional' },
  { q: 'Which initiatives must submit', who: 'Dan',
    blocks: 'Nothing', meanwhile: 'Ignore for now' },
  { q: 'Who performs the canada-ca transfer', who: 'Nick',
    blocks: 'The repo move', meanwhile: 'Asked. An issue on canada-ca/welcome is the route he named' },
  { q: 'What the production intake should be', who: 'TBS',
    blocks: 'Production only', meanwhile: 'The prototype answer is an Azure Function plus one CSP line' },
];
