/**
 * What the tool has to do, as data. `tools/build-requirements.mjs` renders it to
 * NOTES/requirements.html, which is the page people read.
 *
 * Why a data file rather than a hand-written page: every requirement carries an id that gets
 * quoted in conversation, a state that changes as decisions are made, and an owner. Those
 * three things drift the moment they are maintained by hand in prose.
 *
 * States:
 *   'built'    in the tool today
 *   'agreed'   decided, and not built yet
 *   'proposed' our reading, waiting for somebody to confirm it
 *   'open'     nobody has decided
 */

export const updated = '2026-09-17';

export const intro = [
  'This is the standing record of what the GC Enterprise Architecture self-assessment tool has to do. It accumulates: a decision made in a meeting is written here the same day, with who made it.',
  'Each requirement carries a number so it can be quoted, a state, and an owner where somebody owes an answer. Numbers are never reused and never renumbered. Nothing is deleted when a requirement changes: the state changes and the reason goes in the note.',
  'Owners are named people. Build team means Mariia Yermolenko, who is building this on a co-op term at the Treasury Board Secretariat. TBS means whoever holds the decision inside the department, which is Dan Cooper unless the entry says otherwise.',
];

/** Shown under the intro, because a reader will ask what standard this follows. */
export const standard = {
  title: 'What this follows, and where it departs',
  points: [
    ['The standard', 'ISO/IEC/IEEE 29148:2018, Systems and software engineering, life cycle processes, requirements engineering. It replaced IEEE 830, which is withdrawn and still the thing most people picture when they hear the words requirements specification.'],
    ['Tailored, which the standard allows', 'Clause 4.5 permits tailoring. Two departures are deliberate. The document carries a status line where a signature block would go, because it is living and gets baselined at each release. And requirements are written in plain present tense, leaving out the "shall" convention in clause 5.2.7, because the people who read this are two colleagues and a director, and "the tool shall keep work as it is typed" is harder to read than the same sentence without it.'],
    ['States', 'Proposed is the standard word. Agreed means analysed, agreed by whoever owns the decision, and committed to. Built means it is in the tool. Open marks a decision nobody has made, and every open item is also listed in one place at the top.'],
  ],
};

export const sections = [
  {
    id: 'purpose',
    title: 'Purpose and scope',
    lead: 'What the tool replaces and what it does not touch.',
    reqs: [
      { id: 'P1', state: 'agreed', text: 'A department scores its own architecture against the published GC Enterprise Architecture framework and points at evidence it already holds.',
        note: 'Replaces the GC EARB assessment template and the score deck built by hand.' },
      { id: 'P2', state: 'agreed', text: 'The assessor reads the answers that do not add up. Reading all 176 is the job this abolishes.',
        note: 'On a full submission the anomalies are single digits out of 176 questions.' },
      { id: 'P3', state: 'agreed', text: 'Everything in the tool is unclassified. Nothing protected or classified goes into it at all.',
        note: 'Settled with Dan on 1 September 2026. This one decision removes the second deployment, the local-only mode, the theme switch and the recall problem.' },
      { id: 'P4', state: 'open', owner: 'Dan', text: 'Which initiatives have to submit one.',
        note: 'Blocks nothing that is being built.' },
    ],
  },
  {
    id: 'roles',
    title: 'Roles and access',
    lead: 'Three roles, and three views that do not overlap. The prototype shows them in one page because it is a prototype.',
    reqs: [
      { id: 'R1', state: 'agreed', text: 'Three roles: submitter, assessor, admin.' },
      { id: 'R4', state: 'built', text: 'Neither side offers a way into the other.',
        note: 'The submitter home page carried two links across, to the assessor view and to the admin view. They existed to make testing easy before either side worked, and they offered a person who is not an assessor a sign-in they cannot pass. The addresses still reach both, which is how the tests get there. Admin stops being a destination of its own: assessor and admin are one place with tabs inside it.' },
      { id: 'R3', state: 'agreed', owner: 'Mariia', text: 'The submitter side and the assessor side are separate products that share a build. Neither screen may describe the other, and no state carries between them.',
        note: 'They are on one page today for testing, and the crossover links exist for that reason alone. What the finished thing does: the role comes back from the store at sign-in, submitter by default and assessor where an admin has granted it, and a person only ever sees the one side. The sign-in screen now carries nothing from the submitter side, which is where this went wrong first.' },
      { id: 'R2', state: 'built', text: 'The views are separate. A submitter cannot reach the assessor view or the admin view.',
        note: 'They are reachable from one page today so the shape can be shown and argued about. That is a property of the prototype.' },
      { id: 'R3', state: 'agreed', text: 'The admin adds assessors. Signing in tells the tool which role somebody has, and they never choose it themselves.' },
      { id: 'R4', state: 'agreed', text: 'The admin can grant admin rights to an assessor, the way a Discord server grants a role.',
        note: 'So an admin leaving does not leave the programme without one.' },
      { id: 'R5', state: 'agreed', text: 'Rights decide which settings somebody sees.' },
      { id: 'R6', state: 'proposed', text: 'The exact rights each role carries, as a table, before any of it is built.',
        note: 'The Discord model is the reference: named roles, each with a set of permissions, granted per person.' },
      { id: 'R7', state: 'open', owner: 'Dan or Chris', text: 'What an assessor sees of the pool.',
        note: 'Every assessor sees everything today. Chris says departments know who their assessor is, so a department could pick one at submission, and an assessor could share a file or hand it on. A My assessments filter is the shape to add once the rule exists.' },
      { id: 'R8', state: 'open', owner: 'Dan', text: 'Whether admin is a role of its own or an assessor with more buttons.' },
      { id: 'R9', state: 'built', text: 'An admin can delete a record, and has to type the initiative name out to do it.',
        note: 'Copied from the way GitHub deletes a repository. A prototype fills up with test submissions and somebody has to be able to clear them; the protection is the typing, because a confirmation somebody can agree to by reflex stops being one.' },
      { id: 'R10', state: 'agreed', text: 'A submitter can never delete anything.' },
    ],
  },
  {
    id: 'signin',
    title: 'Signing in',
    lead: 'The thing that makes every access rule above enforceable.',
    reqs: [
      { id: 'S1', state: 'agreed', text: 'Real sign-in, so the tool knows who somebody is without asking them.',
        note: 'The no-sign-in design came from the assumption that the tool would hold classified evidence and therefore could not be online at all. P3 removed that assumption, so the constraint went with it.' },
      { id: 'S2', state: 'agreed', text: 'For the real thing, the departmental account: the same one used for Teams.',
        note: 'Microsoft Entra. No new password, and the tool knows the person and their department from the sign-in.' },
      { id: 'S3', state: 'built', text: 'For the prototype, sign in with a Google account, which sends no email and needs no password.',
        note: 'The first plan was a link sent to a work address. Firebase caps that at five sign-in emails a day for the whole project on the free plan, which is three testers, so it cannot be the prototype route. Neither of these sends an email at all. Microsoft matters because it is how Dan tests from his work account, and it may need TBS to allow the sign-in, which Google does not.' },
      { id: 'S6', state: 'proposed', owner: 'Dan, then TBS', text: 'Microsoft sign-in, so Dan can use his work account.',
        note: 'The button is on the screen and the provider is not enabled: Firebase needs an application registered in an Azure directory, which needs somebody with Azure rights at TBS. Google works meanwhile.' },
      { id: 'S7', state: 'built', text: 'Every address the page is served from is registered against the sign-in, in two places.',
        note: 'Firebase authorised domains, and the OAuth client\u2019s authorised redirect URIs and JavaScript origins in Google Cloud. Missing the second gives redirect_uri_mismatch and nothing else explains it. Publishing the tool at a new address means adding it in both places.' },
      { id: 'S8', state: 'open', owner: 'Mariia', text: 'The Firebase web key answers only from the addresses the tool is served from, and only for the three APIs it uses.',
        note: 'The published page carries the key, which is how Firebase is meant to work: it names the project and authorises nothing by itself. GitHub secret scanning flags it anyway, because the same shape of key can carry billable access on other Google APIs. A command-line call reached the project with no site attached, so the key today carries no restriction. The restriction to write is websites myermcat.github.io and localhost, APIs Identity Toolkit, Token Service and Cloud Firestore. What guards the data is the sign-in and the published rules, so this is about somebody else spending the project’s free quota.' },
      { id: 'S28', state: 'built', owner: 'Mariia', text: 'A control that removes something says which thing it removes, and asks before it does.',
        note: 'Reported on 17 September, in the words that matter: she went to the assessor side to delete a test record, pressed the red Close this one, the row went, no window appeared, and the record was still in the store. Two faults in one control. The label named nothing it did: it takes a row off this browser\u2019s list of open submissions, and nothing on that page can remove anything from the store. And with no audit typed against the row it dropped it silently, so the only evidence of what had happened was the row going, which is exactly what deleting would have looked like. It is called Take it off this list now, it is not drawn in the destroying colour, and it always asks. The window says the record stays in the shared store and that removing it for everybody is in the portfolio view. That one is unchanged and already asks for the code to be typed out: the code and not the initiative name, because two departments can share a name, a name can be read off the row above by mistake, and it is the field most likely to be blank.' },
      { id: 'S4', state: 'built', text: 'A build with a provider signs the assessor in and says so. A build without one opens on a screen shaped like a sign-in that says it is a mockup, and everything it produces says nobody checked it.',
        note: 'Corrected 17 September, after the question was asked directly: how can it ever be verified? Two different answers, and the tool was giving the wrong one in both directions. The assessor’s own name is checked on a build with a provider, twice over: the address comes from the provider, and the rules will not list the pool to an address the provider has not verified. The sign-off card printed “unverified” beside it unconditionally, which was not caution but a false statement, while the header two screens away had it right. The submitter’s name cannot be checked at all on the code route, by design, so a badge implying a verified state it can never reach was the wrong word: it now says the name was not checked, and the sentence beside it says what does happen, which is that the tool asks for a name and a work address and refuses an address outside gc.ca and canada.ca. The flag on the record stops being the literal true and records what was actually true: checked only where the address typed is the address somebody is signed in as, because an account existing does not make a typed address that person’s.' },
      { id: 'S27', state: 'built', owner: 'Mariia', text: 'A record named before codes were readable is given a code somebody can be told, on its next save.',
        note: 'Found on 17 September by the one person with a record older than the change. Ids were twenty characters over a 62-symbol alphabet until 14 September. The screen put that name through the code formatter, which uppercases, drops every character the current alphabet excludes and keeps the first twelve, so the results page showed a twelve-character code that named no document. She copied it off her own screen, typed it into Open with an access code, and was told no assessment has it, about an assessment she had just saved online and watched the badge confirm. The formatter now shows a name it would not have minted exactly as it stands, and the next save mints a readable code and writes the record under it. The old document is left where it is, unreachable, which is what it already was: deleting it is an admin\u2019s right and the page does not have it. The name it had is kept on the record as previousId so the copy left behind can be matched to the one that replaced it. The test that let this through asked looksLikeCode, which tidies what a person typed before judging it, so a twenty-character mixed-case name tidied down to twelve characters that were all in the alphabet and answered yes. Judging a stored name is a different question and now has its own function.' },
      { id: 'S25', state: 'built', text: 'One code per assessment, minted when it is created, called the reference code.',
        note: 'Decided 14 September, replacing two codes with one. There was a four-character reference minted at creation for email subject lines, and a twelve-character access code minted at the first online save. Same alphabet, both called a code, sitting centimetres apart on the results page: "give me the code" had two answers. The merged code is minted at creation, which is what the short one always did, so an assessment can be named before it has ever been online and somebody who types a code for an assessment that was never saved is told that in those words. Email subjects quote its first four characters only: a subject line is logged, forwarded, quoted back in replies and answerable to access-to-information, and the whole code opens the assessment. Four characters finds the thread in Outlook and is eight characters short of opening anything. It is never rotated or swapped, because with no owner there is nobody who could be allowed to do it without also letting anybody lock everybody else out.' },
      { id: 'S26', state: 'built', text: 'Anything that replaces the assessment this browser holds makes you tick a box saying you have kept the code.',
        note: 'Asked for on 14 September. The sentence was already on the window and a sentence is something people scroll past; the act of ticking is deliberate in a way reading is not, and the code is beside the box to copy. The same window refuses to commit until it is ticked, and it shakes when somebody presses the button anyway, because a refusal that only adds a line of text is a refusal people miss.' },
      { id: 'S27', state: 'built', text: 'A work email is refused unless it ends in gc.ca or canada.ca.',
        note: 'Changed from a warning on 14 September: a grey line beside the field is read by nobody who did not already know, and a save under a wrong address is a version attributed to somebody who cannot be found. Every federal department is under gc.ca, including the Senate at sen.parl.gc.ca, which is why this is a suffix and not a list of departments that would go stale. An address that differs from the one this browser last saved with is called out beside the field, which is the only defence against somebody accepting the remembered address, deleting half of it by accident and pressing Enter.' },
      { id: 'S23', state: 'built', text: 'Anything that replaces the assessment this browser holds asks first, offers to save it online, and says what would otherwise be lost.',
        note: 'One guard, src/guard.ts, used by all five paths that replace the draft: opening a file, opening by access code, switching question set, discarding, and undoing a discard. It was five windows saying five different things. Three asked and offered a file, one asked and offered nothing, and opening by access code asked nothing at all. Three states: work never saved online has everything to lose, work saved online and edited since has the edits to lose, and an empty form asks nothing, because a window in front of nothing is how people learn to dismiss windows.' },
      { id: 'S23', state: 'built', text: 'Saving online asks who is saving: a name and a work email, every time, kept with that version.',
        note: 'Dan, 14 September. A version used to arrive with nobody attached to it: the owner address is set once when the record is created, and somebody holding the access code left no trace, so an assessor could not tell whose work was in front of them. Typed and checked by nobody, and every screen showing it says unverified, the same way the assessor\u2019s own name always has. Checking it would cost every submitter an account, which is the thing Dan does not want. The browser remembers the last pair and offers them as grey placeholder text: one Tab accepts both and moves to the button, Enter presses it. Offered rather than filled, because a filled field is a claim the tool makes on somebody\u2019s behalf and the second person on a shared machine would save under the first person\u2019s name without reading it. The record keeps the last twenty saves as the version trail the tool has, since a save replaces the document.' },
      { id: 'S24', state: 'built', text: 'The email check refuses only what is not an address at all.',
        note: 'There is no single Government of Canada email domain. The published Email Management Services Configuration Requirements give every public servant two addresses, one at their department and one at canada.ca, and the departmental half differs for every department. The Senate is at sen.parl.gc.ca, two levels below gc.ca; Canada Post is not on gc.ca at all. Duplicate names get a digit, middle initials add a segment, generic mailboxes look nothing like a person. So the blocking rule asks only that it be an address, and an address that is not gc.ca or canada.ca gets a line beside the field saying it will be saved as typed. A form that turns away a real public servant is the worse failure here, because nobody verifies the name anyway.' },
      { id: 'S21', state: 'built', text: 'An assessment carries an access code, which is its own name in the store, twelve characters in three groups of four.',
        note: 'The id and the access code are one value, because the id is the document path and knowing a path is exactly what "may open this one record and nothing else" means. A separate code would need a lookup table and two things to keep in step. Twelve characters from a 32-symbol alphabet with I, O, 0 and 1 removed is 2^60: thirty-six years of guessing at a billion a second, and about a one in a billion chance any two collide at 50,000 assessments. It was twenty characters from a 62-symbol alphabet, which is stronger and unreadable, and somebody has to carry this one over Teams and read it down a phone.' },
      { id: 'S22', state: 'built', text: 'The access code is typed into one box per character, and everything a person might reasonably do with it works.',
        note: 'Paste the whole code into any box with or without dashes and in any case, type it straight through with the focus moving on by itself, backspace out of an empty box into the one before, and arrow between boxes. The dashes are drawn and never typed, and they are hidden from a screen reader, which would otherwise read them as words. A field people fight with is a feature nobody uses.' },
      { id: 'S18', state: 'agreed', owner: 'Mariia, then Dan', text: 'A submitter reaches an assessment with a share code and no account. An assessor and an admin need an account.',
        note: 'Decided on 10 September, after Dan asked whether the tool needs accounts at all. The answer is split, and the reason is mechanical. Firestore rules can read a query\u2019s limit, its offset and its ordering, and nothing about a filter, so no rule can permit "list the assessments matching the code I typed". The only list rules available are an identity test or one that permits everybody, and permitting everybody publishes every department\u2019s draft to anybody who reads the page source. Delete is worse: it is the one destroying right in the tool, so a self-declared admin empties the store. Everything else an account was doing for a submitter, a code does as well or better, and it fixes one thing accounts made worse: today a submitter reaches their own record only through an id in one browser, so clearing a browser loses a submission to its own author.' },
      { id: 'S19', state: 'built', text: 'Both routes stay in the build, and one input picks which one answers.',
        note: 'EARB_ACCESS takes accounts or code, defaults to accounts, and refuses anything else in one sentence. src/who.ts is the single interface every screen asks: who this is, whether the name has been checked, and whether this person may list the pool. Both paths stay compiled, typechecked and covered, because commented-out code is none of those and code that is not typechecked has been abandoned and not kept.' },
      { id: 'S20', state: 'open', owner: 'Mariia', text: 'What a share code must do before it may grant a write.',
        note: 'Partly answered on 17 September. The rule granting update on the code went live that day, and the field mask went in the same day: a save names the fields it changes, so the accidental half of this, two code-holders overwriting each other, is closed. The deliberate half is not, and it needs a rule refusing a write that empties a question. It is acceptable while the people holding codes are three testers, and it is the first thing to answer before anybody outside that group is sent one. Three things stand in front of it, all found on 10 September. A code that grants update is a blanking key: a rule permitting whoever holds it cannot tell a legitimate save from somebody clearing 176 answers, and putAssessment writes the whole document with no field mask, so two code-holders typing at once is last-write-wins over an entire assessment. A8 was a nicety and becomes a precondition. An open read rule also lets an unauthenticated loop spend the whole daily allowance and take the tool offline. And A5, that an assessor cannot change the evidence, survives only if the audit moves to its own document beside the assessment, which the published rules already describe and nothing has ever written to.' },
      { id: 'S14', state: 'agreed', text: 'An assessment is complete when every question in its set carries a score or is marked not applicable, and the six overview fields are filled.',
        note: 'Decided on 8 September. The overview counts as things that have to be filled in, and not as questions: the count on screen stays 176. No floor on how much may be marked not applicable, because an assessment that is not applicable throughout is a thing an assessor should see and judge. The reasoning and the evidence are excluded: no question asks for either, and requiring them would buy typed filler, which the flags already catch from the other direction.' },
      { id: 'S15', state: 'agreed', text: 'An assessor may read an unfinished submission and may do nothing else with it.',
        note: 'Decided on 8 September. No scoring, no verdict, no questions written against it until the submitter says it is finished.' },
      { id: 'S16', state: 'open', owner: 'Mariia', text: 'Whether saying an assessment is finished stops the submitter editing it.',
        note: 'Left open on 8 September, with a leaning towards yes: a locked assessment is how an assessor knows they are not scoring a moving target. What it costs is that a typo becomes a request to somebody else. The alternative, which is what happens today, is that the submitter keeps editing and the assessor screen marks the row as updated.' },
      { id: 'S17', state: 'built', text: 'Only an admin grants a role. An assessor cannot make somebody else an assessor.',
        note: 'The published rules allow create and update on a role document to an admin alone, and no delete to anybody, so nobody can promote themselves or each other. Today that means every assessor account has to come from you.' },
      { id: 'S9', state: 'built', text: 'An account that signs in without an assessor role is told so, by name, with a way onward.',
        note: 'Signing in and being allowed in are two different things. An address nobody has added used to reach the assessor screen and be told the pool was empty, which reads as a lost submission. It now gets one screen: what happened, the address to send to an admin, a way back to the home page, and a way to sign in as somebody else. An assessor who asks for the admin view is turned back the same way.' },
      { id: 'S10', state: 'built', text: 'Sharing an assessment is handing somebody its access code. Whoever holds the code can open it and change it, and nobody without it can.',
        note: 'This replaced a mockup that asked for email addresses, recorded them and granted nothing, which the user found beside the real mechanism and asked which of the two was working. The code is the record\u2019s own name in the store, so there is one thing to share and one thing to hold. It appears as a control you can copy from everywhere it is shown: the results page, the window behind File, the first online save, and every window that might replace the assessment in this browser. The tool sends nothing, and says so wherever the code appears.' },
      { id: 'S21', state: 'agreed', owner: 'Mariia', text: 'Telling somebody about an assessment happens outside the tool.',
        note: 'Decided 14 September. The tool cannot put a message in front of anybody and must never look as though it has. It can open the person\u2019s own mail client with the message and the code already written, which is their client sending, not the tool. The only control that touches an assessor is a mark on the record.' },
      { id: 'S22', state: 'agreed', text: 'A code cannot be taken back.',
        note: 'There is no list of who holds one and no way to withdraw it. Somebody given the code keeps the ability to open and change the assessment, and forwarding it passes the same ability on. Said on the sharing window and in settings, in those words. Withdrawing access would mean a new code and a new record, which is a decision nobody has needed yet.' },
      { id: 'S11', state: 'built', owner: 'Mariia, then TBS', text: 'Somebody holding an access code may open that one assessment and change it, with no account.',
        note: 'Published on 17 September, and checked from outside the same hour: deploy/check-rules.sh with no sign-in at all refuses listing the collection, listing with a page size, reading the roles, creating an assessment and making yourself an admin, and opens one by its code. Until it was published the tool minted a code, showed it, let somebody type it, and Google refused the request, so the code meant nothing on its own. Written on 14 September in deploy/firestore.rules: get on an assessment is granted to anybody who can name the document, because the name is the code, and update is granted on the same basis with the owner\u2019s address, the document kind, the assessor\u2019s verdict and the withdrawal frozen. Listing still needs an account, which is the property that matters: a stranger may open the one assessment whose twelve characters they were sent and may never ask what else is there. The arithmetic is 2^60. Publishing is one paste into the Firebase console by whoever owns the project, and deploy/check-rules.sh checks the result from outside, including that listing is still refused.' },
      { id: 'S12', state: 'agreed', text: 'Holding a code never grants scoring.',
        note: 'The audit is gated on a role document that only an admin writes. If the code widened that, anybody could appoint their own assessor by sending them a code.' },
      { id: 'S13', state: 'open', owner: 'Dan', text: 'Whether an assessment is routed to one named assessor.',
        note: 'Every assessor can already list every submitted assessment, so naming one would be a routing hint and not a permission. Which of the two it is changes what the assessor screen should show. With no naming, the submitter sends their assessor the code and the routing is the message.' },
      { id: 'S5', state: 'agreed', text: 'A submitter may read and change their own submission, and no other.',
        note: 'And any submission they have been added to.' },
    ],
  },
  {
    id: 'instrument',
    title: 'The instrument',
    lead: 'The questions, the weights and the scale. Dan owns the content; the tool renders whatever it is handed.',
    reqs: [
      { id: 'Q6', state: 'built', text: 'A question belongs to its own domain and to any number of named categories. All nine categories TBS named are declared.',
        note: 'Business, Data, Application, Technology, Security, Privacy, Financial, Accessibility and Official Languages, asked for by Dan on 8 September. A question carries a topics array; it counts once in the overall score through its domain, and at full weight inside every topic it carries, which is what lets security weigh differently from business without inflating the total. 44 of 176 carry more than one today. The results page shows the second cut as its own set of bars and says in one line that they do not add up to the overall.' },
      { id: 'Q13', state: 'built', text: 'An assessor sees the same category cut the submitter sees, on the submission in front of them.',
        note: 'Built 17 September. A department that is fine overall and weak on security is the case an assessor exists to catch, and the four domain numbers hide it by dividing those 25 questions four ways. Read-only on that screen: an opinion about a question belongs in the audit, which has its own reasons attached, and a second place to change a score is a second place for the two to disagree.' },
      { id: 'Q12', state: 'built', text: 'Every category on the results page opens onto its own questions, and each one takes you to it.',
        note: 'Built 17 September. A number with nothing behind it has to be taken on trust, and the first thing anybody does with a low category score is ask which questions made it low; before this they had twenty pages to hunt through. The bars stay closed, so the page still reads as a summary, and open in place so nobody loses where they were. Weakest first, because that is the one to act on. Editing in place was the alternative and was rejected: a score needs its 0-to-10 anchors, its stage expectation, its help text, its evidence rows and its justification box, which is most of a question card, and two places to maintain the hardest UI in the tool is two places for them to drift. The question is marked when you arrive, because twenty near-identical cards do not say which one you were brought to.' },
      { id: 'X16', state: 'built', text: 'The built page names no individual.',
        note: 'Asked for on 17 September, in those words: the tool\u2019s own text goes to departments who sat in none of the meetings, and a colleague\u2019s name in it reads as a record about a person. Naming a question set after whoever wrote it is a different thing and stays, because a version is not a sentence about somebody. The gate reads the built file and not the source, because the two differ: the bundler strips JavaScript comments and inlines the stylesheet with its comments intact, so two CSS comments naming somebody shipped while the source looked clean.' },
      { id: 'Q9', state: 'built', text: 'Dan gives his own category assignments in a Topics column in the workbook, and the importer reads it.',
        note: 'Added 14 September. One column per domain sheet, headed Topics, found by its header so it can sit anywhere; the cell holds the categories beyond the question\u2019s own domain, comma or semicolon separated, matched without regard to case or spacing; a blank cell means the question is only about its own domain, which is the common case and costs nobody any typing. A name that is not one of the nine refuses the whole import and says which question and which name, because a mistyped category is the one error nobody can see afterwards: the question counts towards nothing and every screen still renders correctly. The rubric loader refuses the same thing when a file is opened. Until all four sheets carry the column the tool falls back to a keyword pass over the question wording and calls the grouping provisional on every screen that shows it; the badge goes when the column does all four.' },
      { id: 'Q10', state: 'open', owner: 'Dan', text: 'The category assignments themselves.',
        note: 'The mechanism is finished and waiting. All five categories that are not domains are read from the wording of each question and are ours, not his: Security 25, Privacy 8, Financial 13, Accessibility 3, Official Languages 2. Accessibility and Official Languages were reported as empty on 14 September and that was wrong, corrected on 17 September: the sweep counted hits without reading them. Six questions mention something accessible and three are about accessibility; the other three are the FAIR principles\u2019 Accessible and data reaching other departments. The pattern now matches the noun and WCAG and not the adjective. Both categories are thin rather than absent, which the results page says beside the bar, because a score built on two questions moves a long way on one answer.' },
      { id: 'Q11', state: 'open', owner: 'Dan', text: 'Which questions are answered yes or no rather than scored.',
        note: 'Dan named the defect and gave one example. Ten of the 176 read as binary and are marked so in the question set, from a narrow pattern over the wording, which is ours. The workbook now carries an Answer type column holding our reading, with the Answer column beside it offering the matching picker: 0 to 10 for a scale question, Yes and No for the others, N/A on both. Confirming or overruling ten rows is the whole of the ask.' },
      { id: 'Q1', state: 'built', text: 'The question set is a data file. A new version is a new file, and every assessment records the version it was answered against.' },
      { id: 'Q2', state: 'built', text: 'Question sets accumulate. Adding one changes nothing on its own; one set is active at a time; any set can be previewed, made active or deleted.' },
      { id: 'Q3', state: 'built', text: 'A submission is scored against the set it was answered against, and the row says which set produced the number.' },
      { id: 'Q4', state: 'built', text: 'Each question is scored 0 to 10 against a ladder of descriptions, and the ladder is visible while answering.' },
      { id: 'Q5', state: 'built', text: 'Question weight is multiplied by a lifecycle-stage factor, and the weights are re-normalised so every assessment still scores out of 10.' },
      { id: 'Q6', state: 'built', text: 'Not applicable is an answer. It leaves the score out of every total and counts as dealt with for progress.' },
      { id: 'Q7', state: 'proposed', owner: 'Dan', text: 'Ten questions are yes/no. A no colours its question, its section, its rail row and its domain tab, and stops nothing.',
        note: 'Which ten is our reading of his wording, and is labelled provisional in the tool.' },
      { id: 'Q8', state: 'built', owner: 'Dan', text: 'Questions carry topics as well as a domain, so the same answers can be cut across the four domains.',
        note: 'Six topics, 31 questions in two of them. A question counts fully in each topic and once in the overall, so the topic scores do not add up to the overall.' },
      { id: 'Q9', state: 'open', owner: 'Dan', text: 'Per-question criticality, separate from section weight.' },
      { id: 'Q10', state: 'open', owner: 'Dan', text: 'The dropdown answers for each question.',
        note: 'None exist. The only real source is the 700-odd past assessments.' },
      { id: 'Q11', state: 'open', owner: 'Dan', text: 'The Business Architecture section weights add up to 80.',
        note: 'His own workbook, confirmed in his words. The tool shares the missing 20 out proportionally and shows the normalised share.' },
      { id: 'Q12', state: 'open', owner: 'Dan', text: 'The routing thresholds.',
        note: 'He gave three different numbers in one conversation. The tool interpolates and labels the threshold provisional wherever it appears.' },
    ],
  },
  {
    id: 'filling',
    title: 'Filling one in',
    lead: 'The submitter side.',
    reqs: [
      { id: 'F1', state: 'built', text: 'Nobody has to finish it in one go. Work is kept as it is typed, and a reload loses nothing.' },
      { id: 'F2', state: 'built', text: 'One weighted section per screen, with a rail that says where the gaps are.',
        note: '176 questions in one scroll is not a form anybody finishes.' },
      { id: 'F3', state: 'built', text: 'The overview asks six things before the questions: name, department, contact, summary, the marking of the evidence, and the lifecycle stage.' },
      { id: 'F4', state: 'built', text: 'Every assessment carries a four-character reference from the moment it is created, and the reference never changes.',
        note: 'Email subject lines are permanent, so nothing in one may depend on a name somebody can edit.' },
      { id: 'F5', state: 'built', text: 'Nothing is destroyed in one step, and the window that asks says what will be lost and offers a copy first where there is one to offer.' },
      { id: 'F6', state: 'agreed', text: 'Submitting is one deliberate act. The first press names what is about to go online and asks the person to confirm it is unclassified.' },
      { id: 'F7', state: 'agreed', text: 'After the first submit, later changes write through as they are made.' },
    ],
  },
  {
    id: 'evidence',
    title: 'Evidence and markings',
    lead: 'What follows from P3.',
    reqs: [
      { id: 'E1', state: 'built', text: 'Evidence is a link to where the artefact already lives, plus a note that the assessor has been given access.' },
      { id: 'E2', state: 'built', text: 'Evidence is a link, and nothing can be attached to an assessment.',
        note: 'Attaching was removed on 1 September. It cannot survive a store: a document there caps at one mebibyte and the tool allowed fifteen. A file attached by an earlier version still opens, so nothing already saved is lost.' },
      { id: 'E3', state: 'built', text: 'An artefact above unclassified goes to the assessor by email, and the tool writes the subject line and records that it was sent.' },
      { id: 'E4', state: 'built', text: 'Choosing a marking above unclassified takes over the screen once, explains what to do instead, and cannot be dismissed until the person says they understand.' },
      { id: 'E5', state: 'built', text: 'A file attached while a row was unclassified cannot stay once that row is marked higher. Saving is blocked and the row says why.' },
      { id: 'E6', state: 'built', text: 'Evidence marked above the answer given on the overview asks which of the two is wrong.' },
      { id: 'E7', state: 'built', text: 'The document itself is marked unclassified on screen and on every printout, with the evidence marking beside it.' },
    ],
  },
  {
    id: 'assessing',
    title: 'Assessing',
    lead: 'Rules Dan stated as rules.',
    reqs: [
      { id: 'A1', state: 'built', text: 'A changed score cannot be saved without a reason.' },
      { id: 'A2', state: 'built', text: 'Nothing is overwritten. Each change appends a name, a time and the reason, and two assessors disagreeing leaves both accounts.' },
      { id: 'A3', state: 'built', text: 'A line shows that it was edited and by whom before anybody opens anything.' },
      { id: 'A4', state: 'built', text: 'A whole section can be agreed with in one click, which touches no score.' },
      { id: 'A5', state: 'built', text: 'An assessor cannot change the evidence.' },
      { id: 'A6', state: 'built', text: 'The anomalies are surfaced first, with a question drafted for each, and the rest is folded away.' },
      { id: 'A7', state: 'built', text: 'The assessor side keeps its work in the browser as it is typed.' },
      { id: 'A8', state: 'agreed', text: 'Two people on one record do not overwrite each other, and each is told when the other has changed something they are looking at.',
        note: 'The append-only trail is built. The live signal is not.' },
    ],
  },
  {
    id: 'portfolio',
    title: 'The portfolio view',
    lead: 'What the programme sees.',
    reqs: [
      { id: 'D1', state: 'built', text: 'One page over every record: averages by architecture domain, averages by category, and every record listed weakest first.',
        note: 'Corrected 17 September. The two blocks read “Average by domain” and “Average across the domains”, which named two groupings as though they were one thing measured twice, and the second was the category block. It also drew nine bars where the other two screens draw five, because a question set declares its categories and four of them are the four domains repeated: the results page and the submission detail drop those and this page did not, so the four domains appeared twice on one screen with different numbers. The numbers differ because a domain rolls up through section weights and a category is a flat weighted mean over questions. Dropping the four from the label list alone is a worse defect than the one it fixes, since the scores stay as long as the set declares and indexing by position puts one grouping’s number under the other’s name; the page looks each one up by its id.' },
      { id: 'D2', state: 'built', text: 'It recalculates from the answers as it draws, so no stored number can go stale.' },
      { id: 'D3', state: 'built', text: 'It says what it can currently see, and does not pretend to be live when it is reading one browser.' },
      { id: 'D4', state: 'agreed', text: 'Nothing is deleted. A record is withdrawn, which means out of every statistic and still in the list.' },
      { id: 'D5', state: 'open', owner: 'Dan', text: 'The twelve-month questions: per-question averages, averages by department, and the best and worst evidence for each question.',
        note: 'The reason the data is worth collecting at all. All of it needs more than one record to mean anything.' },
    ],
  },
  {
    id: 'data',
    title: 'Data, storage and hosting',
    lead: 'Where the answers live.',
    reqs: [
      { id: 'H1', state: 'built', text: 'Work is kept in the browser as it is typed, and can be saved to a file and reopened.' },
      { id: 'H2', state: 'agreed', text: 'Submitted assessments live in one store that the submitter and the assessor both read, so nobody works from an older copy.' },
      { id: 'H3', state: 'built', text: 'The store address is a build input. It sets both where the page writes and the single host the page is allowed to reach, so a build with no store cannot make a request at all.' },
      { id: 'H4', state: 'built', text: 'The prototype store is Cloud Firestore in Montreal, with sign-in, and rules that let somebody read and write their own records and nothing else.',
        note: 'Live on 1 September in project tbs-earb-self-assessment, region northamerica-northeast1. The rules from deploy/firestore.rules are published, Google sign-in is on, myermcat.github.io is an authorised domain, and roles/yermolenko.maria@gmail.com carries role admin. Free plan.' },
      { id: 'D6', state: 'built', text: 'Saving online is one deliberate act, every time.',
        note: 'Reversed on 14 September, and the reversal is the requirement. The first version sent every keystroke three seconds after typing stopped, once a first button press had turned it on. That is what a document editor does and it is wrong here for three reasons: the copy in the store is what an assessor reads, so it is published and not backed up; a 41 KB document leaving on every pause spends a free-tier allowance that is metered monthly and does not reset overnight; and consent given once for a whole afternoon is not consent anybody remembers giving. The button is the only writer. What the store holds is fingerprinted into the record itself, so a reloaded tab still knows whether the copy online is behind, which module state could not answer. The badge says "Saved online is out of date" in words for as long as it is true, the results page offers Save online again, and marking an assessment ready saves it as part of doing so.' },
      { id: 'H12', state: 'built', text: 'An assessor reading a submission is told when the store has a newer version than the one they opened.',
        note: 'A submission stopped being a thing that holds still the moment saving became continuous. A copy opened last week is a copy of last week, and an audit written against it is written against a version nobody is looking at. The newer one replaces the held one, the audit written here travels across, and the row is marked updated.' },
      { id: 'H10', state: 'agreed', text: 'Attached files do not go into the store as part of the assessment.',
        note: 'A document in Firestore caps at one mebibyte and the tool allows 15 MB per attachment, so the design does not fit by a factor of twenty. Base64 makes it worse by a third. Evidence is a link for exactly this reason; an attachment stays in the file somebody saves, and it does not travel to the store.' },
      { id: 'H11', state: 'open', owner: 'Build team, then Dan', text: 'Whether the prototype store runs on the free plan or has a billing account attached.',
        note: 'The free plan costs nothing and rules out file storage and email sign-in. A billing account at this volume bills a couple of dollars a month. The obstacle is attaching a personal card to government work. That is a procurement conversation, and no amount of engineering settles it.' },
      { id: 'H12', state: 'built', text: 'The store rules are written so that reading your own record costs no extra lookup.',
        note: 'Every exists() or get() inside a rule is a billable read even when the request is denied. Only the assessor and admin paths look a role up.' },
      { id: 'H5', state: 'agreed', text: 'The prototype store has a named owner and a date it gets deleted, both written down before anybody asks.',
        note: 'Drafted, and one blank is yours to fill. Owner of record: Mariia Yermolenko, yermolenko.maria@gmail.com, for the length of the work term. Deleted on: the last day of the work term, which is the date to write in. How it hands over: an admin signs in, opens the portfolio view and exports. The tool already has that feature, so this is a description of something that works today. The free plan has no managed export, so this is the route, and at roughly 40 KB a submission the whole store fits in one file. Confirm the date and this becomes built.' },
      { id: 'H6', state: 'agreed', text: 'The page says what it is whenever it is writing to a prototype store: unclassified drafts only, and not a record of decision.' },
      { id: 'H7', state: 'open', owner: 'TBS', text: 'What the production store is.' },
      { id: 'H8', state: 'open', owner: 'Nick', text: 'The code moving into the canada-ca organisation.',
        note: 'Either as its own repository, which needs permission to create one, or as a folder in TBS-OCIO-ESP, which already publishes a tool the same way and which we can already push to.' },
      { id: 'H9', state: 'open', owner: 'Dan', text: 'Whether the 176 draft questions can be public.',
        note: 'Publishing inside canada-ca makes them public, because Pages will not serve a private repository.' },
    ],
  },
  {
    id: 'notify',
    title: 'Notifications',
    lead: 'Nothing here is built, and one control used to look as though it was.',
    reqs: [
      { id: 'N1', state: 'built', text: 'The tool can open the person\u2019s own mail client with a message already written, carrying the access code.',
        note: 'Their client sends it, not the tool. It used to tell the reader to attach a file the sender had just saved, from when a file was the only way to move an assessment.' },
      { id: 'N2', state: 'agreed', text: 'Notifications go through GC Notify.',
        note: 'Already in Dan own question set, at application question 33.' },
      { id: 'N4', state: 'built', text: 'Saying an assessment is finished writes a mark on the record and notifies nobody.',
        note: 'It was called "Ask an assessor to review it", over a paragraph saying it put the assessment in front of one. It puts nothing in front of anybody: an assessor reading the pool sees "Ready to review" beside the row. It is called "Mark it ready to review" now, it says what the mark does, and it says that telling the assessor is the submitter\u2019s to do and the code is how they get in.' },
      { id: 'N3', state: 'open', owner: 'Dan', text: 'What triggers one, and who receives it.',
        note: 'Submission, assignment, a changed score and a reminder are four different decisions.' },
    ],
  },
  {
    id: 'nonfunctional',
    title: 'How it has to behave',
    lead: 'The properties that are not features.',
    reqs: [
      { id: 'X1', state: 'built', text: 'One self-contained page. No framework, no runtime dependency, and nothing to install at the user end.',
        note: 'Departmental laptops will not run anything that has to be installed.' },
      { id: 'X2', state: 'built', text: 'The page states which hosts it may reach, and the build enforces it.' },
      { id: 'X3', state: 'built', text: 'Every score is reachable and answerable by keyboard, and each score row is one tab stop.' },
      { id: 'X4', state: 'built', text: 'It prints. A printed assessment carries its scores, its reasoning and its marking.' },
      { id: 'X5', state: 'built', text: 'It reads in light and in dark, and on a phone.' },
      { id: 'X6', state: 'agreed', text: 'Only an admin can delete, and only by typing the name of the thing being deleted.',
        note: 'This replaces the earlier rule that nothing could ever be deleted, which does not survive a prototype full of test data.' },
      { id: 'X15', state: 'built', text: 'The results page has one dominant element, one box for anything that blocks, and four regions with no box at all.',
        note: 'It was ten cards of one size, one fill and one width, with the gap between them equal to the padding inside them, so proximity said nothing and the whole page read as one striped surface. The number first, the diagnosis second, the raw record last, and a box around the number only, which is what every results page that works does. The rhythm is the ratio: .5rem inside a part, 1.9rem between parts, 2.9rem and a rule between regions. The gates are numeric relations, because the gate written before this one grepped for a declaration another rule was cancelling and passed on a broken page.' },
      { id: 'X10', state: 'built', text: 'Every screen has an address, and the browser back button behaves.',
        note: 'One hash router. #assessor, #assessor/admin, #results, #settings and a questionnaire stop are all links somebody can send, and Back walks them in the order they were visited. Before this, Back worked inside the questionnaire only: leaving the results page went two stops back into the questions, and an assessor pressing Back was dropped into the submitter view. Held by test/routes.mjs.' },
      { id: 'X11', state: 'built', text: 'The build that gets published is the build that gets tested.',
        note: 'Every suite used to build with no store, so none of the hosted branches ever ran and a page that went blank for anybody signed in reached the live site behind 556 green assertions. test/hosted.mjs now builds with a placeholder project, seeds a session the way a sign-in does, answers Firestore from a stub, and drives the screens a signed-in person meets. tsc is also part of npm test now, which found a type error in the tests themselves on its first run.' },
      { id: 'X12', state: 'built', text: 'The tests run on every push, and nothing publishes without them.',
        note: '.github/workflows/tests.yml runs the seven gates on push and on every pull request. deploy/publish-preview.sh, which is the route that actually reaches people, runs them before it builds and refuses to publish if they fail. Neither existed, which is how a build that broke for anybody signed in reached the live site.' },
      { id: 'X13', state: 'built', text: 'Sign-out is in the header, behind the signed-in identity.',
        note: 'Where GitHub, Google, Microsoft and Canada.ca signed-in services keep it. Settings holds the same control as a second home.' },
      { id: 'X8', state: 'agreed', text: 'Where a decision about how something should behave is not obvious, copy what GitHub does.',
        note: 'Her instruction on 1 September, after the typed-name delete. GitHub has already argued these out in public and its patterns are familiar to the people who will use this.' },
      { id: 'X7', state: 'built', text: 'The page is built to be bilingual: every reader-facing string goes through one function that returns English or French, and the header carries the Canada.ca language control, one link naming the other language in that language.',
        note: 'Keyed on the English text, so no key can be invented or go stale, and a string with no French shows in English and is counted. Settings reports how far the translation has got.' },
      { id: 'X14', state: 'open', owner: 'Mariia', text: 'Whether a submitter may remove their own record from the store before it is reviewed.',
        note: 'Continuous saving means discarding a draft, switching question set or opening another file each leaves a live document online that the submitter can no longer reach and cannot delete, because delete is admin-only. The screens now say so. The alternative is one line in the rules letting an owner delete a record that has not been marked ready. Somebody has to decide which way it goes.' },
      { id: 'X9', state: 'agreed', owner: 'Build team', text: 'The French text itself, for about 610 of 749 reader-facing strings.',
        note: 'Mechanical from here: each string gets its French beside the English. It is writing, and the architecture is done.' },
      { id: 'X10', state: 'open', owner: 'Dan', text: 'French for the question set: 176 questions, their descriptions and the eleven rungs of the scale.',
        note: 'His text, so his translation. It belongs in the rubric file beside the English, which the tool already reads as data.' },
    ],
  },
];

/**
 * How a requirement gets checked, which is the section ISO 29148 expects and the one most
 * requirements documents leave out. It is worth having because the answer here is mechanical.
 */
/**
 * Risks we have looked at and accepted.
 *
 * A risk register is the conventional home for this, and it is a separate thing from a
 * requirement: a requirement says what the tool must do, and a risk says what could go wrong
 * anyway, how likely it is, what it would cost, and who decided to carry it. The one that
 * matters to a reviewer is the last column. An unowned risk is a surprise waiting; an accepted
 * one is a decision.
 *
 * Accepted does not mean solved. Each of these stays here until the mitigation is built or the
 * risk goes away, and the date says when somebody last looked at it.
 */
export const risks = {
  title: 'Risks we have accepted',
  lead: 'What could go wrong that we are choosing to carry, why it is bearable at this stage, and who said so. A risk leaves this list when it is mitigated or when it stops being possible.',
  rows: [
    {
      id: 'RK1',
      what: 'Somebody scripts requests against the store and takes the tool offline.',
      because: 'The rule that makes an access code work grants a read on the document\u2019s name, so an unauthenticated request reaches the store. Nothing in Firestore rate-limits by address, security rules cannot count, and the free plan has no spend cap and no alert unless the project is upgraded to pay-as-you-go, which is a decision for TBS and not for us.',
      likelihood: 'Low',
      cost: 'Two different failures. The daily read allowance is 50,000 and resets overnight, so the tool stops answering until midnight Pacific. The monthly one is 10 GiB of outbound traffic, which at 41 KB an assessment is about 256,000 reads, and exceeding it turns Firestore off for the rest of the calendar month with no remedy but upgrading mid-incident. Nothing is lost and nothing is exposed either way.',
      doing: 'Accepting it, and the reasoning changed on 14 September when the numbers were checked. Listing is what makes this cheap for an attacker, and listing still needs an account: without it a script has to name a document, which is twelve characters from a 32-symbol alphabet, and 2^60 guesses is not a route to anything. App Check was the conventional answer and was examined and rejected: it cannot be expressed in a security rule, it needs a third-party script from Google on a page whose whole policy is default-src none, it draws a badge that lands in the accessibility audit of a Government of Canada service, its free tier is 10,000 assessments a month for the whole organisation and it spends them on a refresh timer rather than per visit, and Google documents the header it rides on only for backends you own and never for the Firestore REST API, so there is no published evidence it would apply to this page at all. Anonymous sign-in was examined and rejected too: it costs an attacker one extra request and adds a second endpoint that can be flooded, whose only kill switch is the feature itself.',
      accepted: 'Mariia, 14 September 2026',
    },
    {
      id: 'RK2',
      what: 'An access code reaches somebody it was never meant to reach, and cannot be taken back.',
      because: 'A code is a bearer token: whoever holds it opens that assessment and can change it. Forwarded once it is permanent, there is no list of who holds it, and there is no way to mint a new one for the same record.',
      likelihood: 'Medium',
      cost: 'One assessment is readable and writable by one more person than intended. The assessment itself is Unclassified, and what it holds is typed reasoning and the titles and locations of evidence, which can name artefacts marked above Unclassified even though no such artefact is kept in the tool. Treat a leaked code as a disclosure of the assessment.',
      doing: 'Saying so plainly, in those words, on the sharing window and in settings, so nobody learns it from an incident. A revocation switch was designed and rejected on 14 September: the page sends the whole document on every save, so any save from a copy that predates the switch would have deleted it and turned the code back on with nothing on screen saying so. A control that reports success without firing is worse than none. The real answer is code rotation, which means a new document and a new code, and it is the next thing to build here.',
      accepted: 'Mariia, 14 September 2026',
    },
    {
      id: 'RK7',
      what: 'Somebody scripts the creation of assessments and fills the free storage.',
      because: 'An assessment has its code before it has ever been online, so the first save is a create by somebody who may have no account. Requiring one would put the account back on the submitter, which is the thing this design removes.',
      likelihood: 'Low',
      cost: 'Documents nobody wants, against 20,000 writes a day and 1 GiB. An admin deletes them.',
      doing: 'The store asks for two things on a create, and neither is a security control: the document name has to be a code this tool would mint, and the body has to carry the five parts of an assessment. They stop the collection being used as free storage for something else. Nothing in Firestore rate-limits by address and security rules cannot count, so there is no version of this that is closed rather than expensive.',
      accepted: 'Mariia, 14 September 2026',
    },
    {
      id: 'RK8',
      what: 'The trail says who saved a version and not what changed in it.',
      because: 'A save replaces the document. Keeping whole versions would mean 41 KB each inside a record that has to stay one document.',
      likelihood: 'Certain',
      cost: 'An assessor can see that a score moved between two saves and cannot see which answer moved it without asking.',
      doing: 'The trail keeps who, when, what it scored and how many questions were answered, which is enough to see a number move and to go and ask the person who moved it. Twenty saves, and when it fills, the ordinary ones go first: the save where the assessment first reached TBS and every time it was marked ready or unmarked are kept, because those are the ones somebody asks about. Answer-level history needs a subcollection and is its own piece of work.',
      accepted: 'Mariia, 14 September 2026',
    },
    {
      id: 'RK9',
      what: 'Somebody holding a code empties an assessment, and every answer is gone.',
      because: 'The published rules grant update to whoever can name the document, and the name is the code. A rule cannot tell a legitimate save from somebody clearing 176 answers: it sees one write of one document by somebody entitled to write it. putAssessment sends the whole document with no field mask, so the ordinary save already replaces everything, and an emptied assessment is a save like any other. Two people typing at once is the same mechanism without the malice, and the later save wins over the whole record.',
      likelihood: 'Low',
      cost: 'An assessment is back to blank, in the store, where the assessor reads it. The browser that did the emptying has the blank version too, so reopening it recovers nothing. Anybody else who still has the work on their own machine can save it back; if nobody does, it is a rebuild from the file somebody last saved, and if nobody saved a file it is 176 questions answered again.',
      doing: 'Half built on 17 September, and the built half is the one that was going to happen by accident. A save now names the fields it changes and Firestore leaves the rest of the document alone, so two people working from one code no longer overwrite each other by taking turns pressing Save, and a save can no longer carry away an answer nobody touched. The comparison is against what that browser last sent; a browser that has never sent this record reads the document first, which costs one read and is the only way to know what is being left alone. What is still open is the deliberate version: somebody who means to empty an assessment can mask every answer and send nothing under each path. That needs a rule refusing a write that empties a question, and it is a rule that can be written. The save trail shows the drop afterwards, because it records how many questions each save left answered, and it holds nothing that could put them back.',
      accepted: 'Mariia, 17 September 2026',
    },
    {
      id: 'RK5',
      what: 'Somebody holding a code changes an assessment in a way its owner never sees.',
      because: 'The code grants a write, which is what sharing means here, and the tool cannot tell a co-author from a stranger who was forwarded the message.',
      likelihood: 'Low',
      cost: 'An answer, a justification or a piece of evidence is different from what the owner left, with nothing on screen saying who changed it.',
      doing: 'Four fields are frozen against anybody who is not the owner, and Google enforces it rather than the page hoping: the owner\u2019s address, so a record cannot change hands; what kind of document it is, so it cannot be hidden from the assessor\u2019s list; the assessor\u2019s verdict; and the withdrawal. The five structural parts of the document must all be present, so a one-field write cannot reduce it to a stub. What is deliberately not frozen is the ready mark, because a co-author holding the code is somebody working on the assessment. There is no per-field history, and adding one is the version-history work that is already on the list.',
      accepted: 'Mariia, 14 September 2026',
    },
    {
      id: 'RK6',
      what: 'The assessment in the store is older than the one on the submitter\u2019s screen when an assessor reads it.',
      because: 'Saving online is one deliberate act each time, on purpose. Anything typed after the last save is on one computer until somebody presses the button again.',
      likelihood: 'Certain',
      cost: 'An assessor scores a version that has moved on, or a laptop failure loses the work since the last save.',
      doing: 'The badge in the header says the copy online is out of date, in words, on every screen, for as long as it is true. The results page offers Save online again whenever the store is behind. Marking an assessment ready saves it as part of doing so, so the version an assessor is told to read is the version they get. The assessor\u2019s own list already flags a row whose stored version is newer than the one they opened.',
      accepted: 'Mariia, 14 September 2026',
    },
    {
      id: 'RK3',
      what: 'A name on an audit entry is not the person who wrote it.',
      because: 'On the code route a name is typed and checked by nobody.',
      likelihood: 'Low',
      cost: 'The record says who scored a question and cannot prove it.',
      doing: 'Every name the tool has not checked is stamped unverified, in the file and on screen, so nothing can later be mistaken for a checked one. Nothing in this process depends on the name being true.',
      accepted: 'Dan and Mariia, 8 September 2026',
    },
    {
      id: 'RK4',
      what: 'The prototype store has no owner of record inside TBS.',
      because: 'It is a personal Firebase project on a free plan, made so the tool could be tried at all.',
      likelihood: 'Certain, until somebody takes it',
      cost: 'A reviewer asks who owns the data and there is no departmental answer.',
      doing: 'Owner of record written down, a deletion date at the end of the work term, and the whole store exports from the portfolio view in an afternoon. H5 carries the text.',
      accepted: 'Mariia, 3 September 2026',
    },
  ],
};

export const verification = {
  title: 'How each requirement gets checked',
  lead: 'Four gates run on every change, and a requirement is not built until the gate that covers it passes. A fifth runs against the live store when the rules change.',
  gates: [
    ['The prose gate', 'Every word the reader sees is checked against the writing rules: no em dashes, no antithesis, no banned words. It runs before the tests and fails the build.'],
    ['The logic gate', 'Scoring, banding, weighting, the flags, the CSV round trip. It runs against the modules directly.'],
    ['The interface gate', 'The built page is driven in a real document object model, end to end: 21 pages of questions answered, evidence attached, markings set, dialogs opened and their buttons pressed. Around 500 assertions, and this is where a requirement about behaviour is actually held.'],
    ['The print gate', 'A printed assessment is checked for the things that vanish on paper: the scores, the reasoning, the marking, and every folded section.'],
    ['The rules gate', 'deploy/check-rules.sh calls the live store four times with no sign-in at all: read every assessment, read the roles, write an assessment, make yourself an admin. All four have to come back refused. A rules mistake cannot be seen from inside the tool, because the tool always has somebody signed in, so this one runs from outside. As of 3 September all four are refused.'],
  ],
  note: 'What no gate covers: anything needing a sign-in or a second person. Those requirements are marked agreed, and they say so.',
};
